# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from dragLabel import DragLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1313, 922)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.argument_label_23 = DragLabel(self.centralwidget, 320, 290)
        self.argument_label_23.setGeometry(QtCore.QRect(320, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_23.setFont(font)
        self.argument_label_23.setObjectName("argument_label_23")
        self.argument_label_12 = DragLabel(self.centralwidget, 220, 240)
        self.argument_label_12.setGeometry(QtCore.QRect(210, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_12.setFont(font)
        self.argument_label_12.setObjectName("argument_label_12")
        self.argument_label_33 = DragLabel(self.centralwidget, 320, 340)
        self.argument_label_33.setGeometry(QtCore.QRect(360, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_33.setFont(font)
        self.argument_label_33.setObjectName("argument_label_33")
        self.answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.answer_label_2.setGeometry(QtCore.QRect(430, 70, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_2.setFont(font)
        self.answer_label_2.setObjectName("answer_label_2")
        self.answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.answer_label_3.setGeometry(QtCore.QRect(490, 120, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_3.setFont(font)
        self.answer_label_3.setObjectName("answer_label_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.argument_label_32 = DragLabel(self.centralwidget, 220, 340)
        self.argument_label_32.setGeometry(QtCore.QRect(230, 120, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_32.setFont(font)
        self.argument_label_32.setObjectName("argument_label_32")
        self.answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.answer_label_1.setGeometry(QtCore.QRect(430, 20, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_1.setFont(font)
        self.answer_label_1.setObjectName("answer_label_1")
        self.argument_label_13 = DragLabel(self.centralwidget, 320, 240)
        self.argument_label_13.setGeometry(QtCore.QRect(320, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_13.setFont(font)
        self.argument_label_13.setObjectName("argument_label_13")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(350, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.argument_label_11 = DragLabel(self.centralwidget, 120, 240)
        self.argument_label_11.setGeometry(QtCore.QRect(100, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_11.setFont(font)
        self.argument_label_11.setObjectName("argument_label_11")
        self.argument_label_31 = DragLabel(self.centralwidget, 120, 340)
        self.argument_label_31.setGeometry(QtCore.QRect(100, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_31.setFont(font)
        self.argument_label_31.setObjectName("argument_label_31")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(150, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.argument_label_22 = DragLabel(self.centralwidget, 220, 290)
        self.argument_label_22.setGeometry(QtCore.QRect(210, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_22.setFont(font)
        self.argument_label_22.setObjectName("argument_label_22")
        self.argument_label_21 = DragLabel(self.centralwidget, 120, 290)
        self.argument_label_21.setGeometry(QtCore.QRect(100, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_21.setFont(font)
        self.argument_label_21.setObjectName("argument_label_21")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(350, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 900, 94, 27))
        self.pushButton.setObjectName("pushButton")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 300, 51, 41))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(110, 230, 20, 171))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(410, 230, 20, 171))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.label_14.setObjectName("label_14")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(420, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.main_det_label.setGeometry(QtCore.QRect(460, 280, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_label.setFont(font)
        self.main_det_label.setText("")
        self.main_det_label.setObjectName("main_det_label")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(820, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(820, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(610, 280, 51, 41))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.label_37.setObjectName("label_37")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(720, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.det_1 = QtWidgets.QLabel(self.centralwidget)
        self.det_1.setGeometry(QtCore.QRect(1060, 270, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_1.setFont(font)
        self.det_1.setText("")
        self.det_1.setObjectName("det_1")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(1010, 230, 20, 171))
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(720, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(920, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(720, 340, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(920, 340, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(710, 230, 20, 171))
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(920, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(820, 340, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(660, 300, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(320, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(320, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(120, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.det_2 = QtWidgets.QLabel(self.centralwidget)
        self.det_2.setGeometry(QtCore.QRect(450, 470, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_2.setFont(font)
        self.det_2.setText("")
        self.det_2.setObjectName("det_2")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(110, 430, 20, 171))
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(220, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(220, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(120, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(220, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(60, 510, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(410, 430, 20, 171))
        self.label_60.setText("")
        self.label_60.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(320, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(10, 490, 51, 41))
        self.label_62.setText("")
        self.label_62.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(120, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.det_3 = QtWidgets.QLabel(self.centralwidget)
        self.det_3.setGeometry(QtCore.QRect(1060, 460, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_3.setFont(font)
        self.det_3.setText("")
        self.det_3.setObjectName("det_3")
        self.label_64 = QtWidgets.QLabel(self.centralwidget)
        self.label_64.setGeometry(QtCore.QRect(820, 480, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.centralwidget)
        self.label_65.setGeometry(QtCore.QRect(720, 530, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.label_67 = QtWidgets.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(1010, 420, 20, 171))
        self.label_67.setText("")
        self.label_67.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(820, 530, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.label_70 = QtWidgets.QLabel(self.centralwidget)
        self.label_70.setGeometry(QtCore.QRect(710, 420, 20, 171))
        self.label_70.setText("")
        self.label_70.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(720, 480, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(660, 510, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(720, 430, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(610, 480, 51, 41))
        self.label_74.setText("")
        self.label_74.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(920, 430, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(820, 430, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(920, 480, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(920, 530, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(290, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(200, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(280, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(330, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(410, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(460, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(400, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(420, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_79 = QtWidgets.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(70, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(70, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(670, 290, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_69 = QtWidgets.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(670, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(1020, 290, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_66 = QtWidgets.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(1020, 480, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "="))
        self.argument_label_23.setText(_translate("MainWindow", "6"))
        self.argument_label_12.setText(_translate("MainWindow", "1"))
        self.argument_label_33.setText(_translate("MainWindow", "18"))
        self.answer_label_2.setText(_translate("MainWindow", "132"))
        self.answer_label_3.setText(_translate("MainWindow", "536"))
        self.label_3.setText(_translate("MainWindow", "+"))
        self.argument_label_32.setText(_translate("MainWindow", "23"))
        self.answer_label_1.setText(_translate("MainWindow", "77"))
        self.argument_label_13.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "x2"))
        self.label_2.setText(_translate("MainWindow", "x1"))
        self.label_17.setText(_translate("MainWindow", "x3"))
        self.argument_label_11.setText(_translate("MainWindow", "5"))
        self.argument_label_31.setText(_translate("MainWindow", "12"))
        self.label_18.setText(_translate("MainWindow", "x1"))
        self.argument_label_22.setText(_translate("MainWindow", "3"))
        self.argument_label_21.setText(_translate("MainWindow", "4"))
        self.label_4.setText(_translate("MainWindow", "x1"))
        self.label.setText(_translate("MainWindow", "x2"))
        self.label_24.setText(_translate("MainWindow", "x3"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_33.setText(_translate("MainWindow", "="))
        self.label_34.setText(_translate("MainWindow", "100"))
        self.label_35.setText(_translate("MainWindow", "100"))
        self.label_39.setText(_translate("MainWindow", "100"))
        self.label_41.setText(_translate("MainWindow", "100"))
        self.label_42.setText(_translate("MainWindow", "100"))
        self.label_43.setText(_translate("MainWindow", "100"))
        self.label_44.setText(_translate("MainWindow", "100"))
        self.label_46.setText(_translate("MainWindow", "100"))
        self.label_47.setText(_translate("MainWindow", "100"))
        self.label_48.setText(_translate("MainWindow", "1"))
        self.label_49.setText(_translate("MainWindow", "100"))
        self.label_50.setText(_translate("MainWindow", "100"))
        self.label_52.setText(_translate("MainWindow", "100"))
        self.label_54.setText(_translate("MainWindow", "100"))
        self.label_55.setText(_translate("MainWindow", "100"))
        self.label_56.setText(_translate("MainWindow", "100"))
        self.label_57.setText(_translate("MainWindow", "100"))
        self.label_58.setText(_translate("MainWindow", "2"))
        self.label_61.setText(_translate("MainWindow", "100"))
        self.label_63.setText(_translate("MainWindow", "100"))
        self.label_64.setText(_translate("MainWindow", "100"))
        self.label_65.setText(_translate("MainWindow", "100"))
        self.label_68.setText(_translate("MainWindow", "100"))
        self.label_71.setText(_translate("MainWindow", "100"))
        self.label_72.setText(_translate("MainWindow", "3"))
        self.label_73.setText(_translate("MainWindow", "100"))
        self.label_75.setText(_translate("MainWindow", "100"))
        self.label_76.setText(_translate("MainWindow", "100"))
        self.label_77.setText(_translate("MainWindow", "100"))
        self.label_78.setText(_translate("MainWindow", "100"))
        self.label_8.setText(_translate("MainWindow", "+"))
        self.label_6.setText(_translate("MainWindow", "+"))
        self.label_10.setText(_translate("MainWindow", "+"))
        self.label_19.setText(_translate("MainWindow", "+"))
        self.label_20.setText(_translate("MainWindow", "x2"))
        self.label_21.setText(_translate("MainWindow", "+"))
        self.label_23.setText(_translate("MainWindow", "x3"))
        self.label_22.setText(_translate("MainWindow", "="))
        self.label_16.setText(_translate("MainWindow", "="))
        self.label_59.setText(_translate("MainWindow", "="))
        self.label_79.setText(_translate("MainWindow", "="))
        self.label_51.setText(_translate("MainWindow", "="))
        self.label_36.setText(_translate("MainWindow", "="))
        self.label_69.setText(_translate("MainWindow", "="))
        self.label_38.setText(_translate("MainWindow", "="))
        self.label_66.setText(_translate("MainWindow", "="))
