# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from dragLabel import DragLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1833, 922)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 810, 94, 27))
        self.pushButton.setObjectName("pushButton")
        self.main_det_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.main_det_triangle_label.setGeometry(QtCore.QRect(240, 300, 51, 41))
        self.main_det_triangle_label.setText("")
        self.main_det_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.main_det_triangle_label.setObjectName("main_det_triangle_label")
        self.main_det_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_brice_label_1.setGeometry(QtCore.QRect(330, 230, 20, 171))
        self.main_det_brice_label_1.setText("")
        self.main_det_brice_label_1.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.main_det_brice_label_1.setObjectName("main_det_brice_label_1")
        self.main_det_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_brice_label_2.setGeometry(QtCore.QRect(640, 230, 20, 171))
        self.main_det_brice_label_2.setText("")
        self.main_det_brice_label_2.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.main_det_brice_label_2.setObjectName("main_det_brice_label_2")
        self.main_det_equals_2 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_equals_2.setGeometry(QtCore.QRect(640, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_equals_2.setFont(font)
        self.main_det_equals_2.setObjectName("main_det_equals_2")
        self.main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.main_det_label.setGeometry(QtCore.QRect(680, 280, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_label.setFont(font)
        self.main_det_label.setText("")
        self.main_det_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.main_det_label.setObjectName("main_det_label")
        self.det1_argument_22_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_22_label.setGeometry(QtCore.QRect(440, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_22_label.setFont(font)
        self.det1_argument_22_label.setText("")
        self.det1_argument_22_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det1_argument_22_label.setObjectName("det1_argument_22_label")
        self.det1_argument_12_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_12_label.setGeometry(QtCore.QRect(440, 440, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_12_label.setFont(font)
        self.det1_argument_12_label.setText("")
        self.det1_argument_12_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det1_argument_12_label.setObjectName("det1_argument_12_label")
        self.det1_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_triangle_label.setGeometry(QtCore.QRect(230, 480, 51, 41))
        self.det1_triangle_label.setText("")
        self.det1_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.det1_triangle_label.setObjectName("det1_triangle_label")
        self.det1_answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det1_answer_label_1.setGeometry(QtCore.QRect(340, 440, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_answer_label_1.setFont(font)
        self.det1_answer_label_1.setText("")
        self.det1_answer_label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det1_answer_label_1.setObjectName("det1_answer_label_1")
        self.det_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det_1_label.setGeometry(QtCore.QRect(680, 470, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_1_label.setFont(font)
        self.det_1_label.setText("")
        self.det_1_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.det_1_label.setObjectName("det_1_label")
        self.det1_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det1_brice_label_2.setGeometry(QtCore.QRect(640, 430, 20, 171))
        self.det1_brice_label_2.setText("")
        self.det1_brice_label_2.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det1_brice_label_2.setObjectName("det1_brice_label_2")
        self.det1_answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det1_answer_label_2.setGeometry(QtCore.QRect(340, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_answer_label_2.setFont(font)
        self.det1_answer_label_2.setText("")
        self.det1_answer_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det1_answer_label_2.setObjectName("det1_answer_label_2")
        self.det1_argument_13_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_13_label.setGeometry(QtCore.QRect(540, 440, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_13_label.setFont(font)
        self.det1_argument_13_label.setText("")
        self.det1_argument_13_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det1_argument_13_label.setObjectName("det1_argument_13_label")
        self.det1_answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.det1_answer_label_3.setGeometry(QtCore.QRect(340, 540, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_answer_label_3.setFont(font)
        self.det1_answer_label_3.setText("")
        self.det1_answer_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det1_answer_label_3.setObjectName("det1_answer_label_3")
        self.det1_argument_33_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_33_label.setGeometry(QtCore.QRect(540, 540, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_33_label.setFont(font)
        self.det1_argument_33_label.setText("")
        self.det1_argument_33_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det1_argument_33_label.setObjectName("det1_argument_33_label")
        self.det1_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det1_brice_label_1.setGeometry(QtCore.QRect(330, 430, 20, 171))
        self.det1_brice_label_1.setText("")
        self.det1_brice_label_1.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det1_brice_label_1.setObjectName("det1_brice_label_1")
        self.det1_argument_23_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_23_label.setGeometry(QtCore.QRect(540, 490, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_23_label.setFont(font)
        self.det1_argument_23_label.setText("")
        self.det1_argument_23_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det1_argument_23_label.setObjectName("det1_argument_23_label")
        self.det1_argument_32_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_32_label.setGeometry(QtCore.QRect(440, 540, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_32_label.setFont(font)
        self.det1_argument_32_label.setText("")
        self.det1_argument_32_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det1_argument_32_label.setObjectName("det1_argument_32_label")
        self.det1_index_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_index_label.setGeometry(QtCore.QRect(280, 500, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.det1_index_label.setFont(font)
        self.det1_index_label.setObjectName("det1_index_label")
        self.det2_argument_33_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_33_label.setGeometry(QtCore.QRect(1320, 330, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_33_label.setFont(font)
        self.det2_argument_33_label.setText("")
        self.det2_argument_33_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det2_argument_33_label.setObjectName("det2_argument_33_label")
        self.det2_argument_13_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_13_label.setGeometry(QtCore.QRect(1320, 230, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_13_label.setFont(font)
        self.det2_argument_13_label.setText("")
        self.det2_argument_13_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det2_argument_13_label.setObjectName("det2_argument_13_label")
        self.det2_argument_11_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_11_label.setGeometry(QtCore.QRect(1120, 230, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_11_label.setFont(font)
        self.det2_argument_11_label.setText("")
        self.det2_argument_11_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det2_argument_11_label.setObjectName("det2_argument_11_label")
        self.det_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det_2_label.setGeometry(QtCore.QRect(1460, 260, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_2_label.setFont(font)
        self.det_2_label.setText("")
        self.det_2_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.det_2_label.setObjectName("det_2_label")
        self.det2_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det2_brice_label_1.setGeometry(QtCore.QRect(1110, 220, 20, 171))
        self.det2_brice_label_1.setText("")
        self.det2_brice_label_1.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det2_brice_label_1.setObjectName("det2_brice_label_1")
        self.det2_answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.det2_answer_label_3.setGeometry(QtCore.QRect(1220, 330, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_answer_label_3.setFont(font)
        self.det2_answer_label_3.setText("")
        self.det2_answer_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det2_answer_label_3.setObjectName("det2_answer_label_3")
        self.det2_answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det2_answer_label_1.setGeometry(QtCore.QRect(1220, 230, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_answer_label_1.setFont(font)
        self.det2_answer_label_1.setText("")
        self.det2_answer_label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det2_answer_label_1.setObjectName("det2_answer_label_1")
        self.det2_argument_21_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_21_label.setGeometry(QtCore.QRect(1120, 280, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_21_label.setFont(font)
        self.det2_argument_21_label.setText("")
        self.det2_argument_21_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det2_argument_21_label.setObjectName("det2_argument_21_label")
        self.det2_answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det2_answer_label_2.setGeometry(QtCore.QRect(1220, 280, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_answer_label_2.setFont(font)
        self.det2_answer_label_2.setText("")
        self.det2_answer_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det2_answer_label_2.setObjectName("det2_answer_label_2")
        self.det2_index_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_index_label.setGeometry(QtCore.QRect(1060, 300, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.det2_index_label.setFont(font)
        self.det2_index_label.setObjectName("det2_index_label")
        self.det2_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det2_brice_label_2.setGeometry(QtCore.QRect(1420, 220, 20, 171))
        self.det2_brice_label_2.setText("")
        self.det2_brice_label_2.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det2_brice_label_2.setObjectName("det2_brice_label_2")
        self.det2_argument_23_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_23_label.setGeometry(QtCore.QRect(1320, 280, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_23_label.setFont(font)
        self.det2_argument_23_label.setText("")
        self.det2_argument_23_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det2_argument_23_label.setObjectName("det2_argument_23_label")
        self.det2_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_triangle_label.setGeometry(QtCore.QRect(1010, 280, 51, 41))
        self.det2_triangle_label.setText("")
        self.det2_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.det2_triangle_label.setObjectName("det2_triangle_label")
        self.det2_argument_31_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_31_label.setGeometry(QtCore.QRect(1120, 330, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_31_label.setFont(font)
        self.det2_argument_31_label.setText("")
        self.det2_argument_31_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det2_argument_31_label.setObjectName("det2_argument_31_label")
        self.det_3_label = QtWidgets.QLabel(self.centralwidget)
        self.det_3_label.setGeometry(QtCore.QRect(1460, 460, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_3_label.setFont(font)
        self.det_3_label.setText("")
        self.det_3_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.det_3_label.setObjectName("det_3_label")
        self.det3_argument_22_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_22_label.setGeometry(QtCore.QRect(1220, 480, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_22_label.setFont(font)
        self.det3_argument_22_label.setText("")
        self.det3_argument_22_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det3_argument_22_label.setObjectName("det3_argument_22_label")
        self.det3_argument_31_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_31_label.setGeometry(QtCore.QRect(1120, 530, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_31_label.setFont(font)
        self.det3_argument_31_label.setText("")
        self.det3_argument_31_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det3_argument_31_label.setObjectName("det3_argument_31_label")
        self.det3_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det3_brice_label_2.setGeometry(QtCore.QRect(1420, 420, 20, 171))
        self.det3_brice_label_2.setText("")
        self.det3_brice_label_2.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det3_brice_label_2.setObjectName("det3_brice_label_2")
        self.det3_argument_32_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_32_label.setGeometry(QtCore.QRect(1220, 530, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_32_label.setFont(font)
        self.det3_argument_32_label.setText("")
        self.det3_argument_32_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det3_argument_32_label.setObjectName("det3_argument_32_label")
        self.det3_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det3_brice_label_1.setGeometry(QtCore.QRect(1110, 420, 20, 171))
        self.det3_brice_label_1.setText("")
        self.det3_brice_label_1.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det3_brice_label_1.setObjectName("det3_brice_label_1")
        self.det3_argument_21_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_21_label.setGeometry(QtCore.QRect(1120, 480, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_21_label.setFont(font)
        self.det3_argument_21_label.setText("")
        self.det3_argument_21_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det3_argument_21_label.setObjectName("det3_argument_21_label")
        self.det3_index_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_index_label.setGeometry(QtCore.QRect(1060, 510, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.det3_index_label.setFont(font)
        self.det3_index_label.setObjectName("det3_index_label")
        self.det3_argument_11_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_11_label.setGeometry(QtCore.QRect(1120, 430, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_11_label.setFont(font)
        self.det3_argument_11_label.setText("")
        self.det3_argument_11_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det3_argument_11_label.setObjectName("det3_argument_11_label")
        self.det3_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_triangle_label.setGeometry(QtCore.QRect(1010, 480, 51, 41))
        self.det3_triangle_label.setText("")
        self.det3_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.det3_triangle_label.setObjectName("det3_triangle_label")
        self.det3_answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det3_answer_label_1.setGeometry(QtCore.QRect(1320, 430, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_answer_label_1.setFont(font)
        self.det3_answer_label_1.setText("")
        self.det3_answer_label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det3_answer_label_1.setObjectName("det3_answer_label_1")
        self.det3_argument_12_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_12_label.setGeometry(QtCore.QRect(1220, 430, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_12_label.setFont(font)
        self.det3_argument_12_label.setText("")
        self.det3_argument_12_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det3_argument_12_label.setObjectName("det3_argument_12_label")
        self.det3_answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det3_answer_label_2.setGeometry(QtCore.QRect(1320, 480, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_answer_label_2.setFont(font)
        self.det3_answer_label_2.setText("")
        self.det3_answer_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det3_answer_label_2.setObjectName("det3_answer_label_2")
        self.det3_answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.det3_answer_label_3.setGeometry(QtCore.QRect(1320, 530, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_answer_label_3.setFont(font)
        self.det3_answer_label_3.setText("")
        self.det3_answer_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.det3_answer_label_3.setObjectName("det3_answer_label_3")
        self.det2_equals_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_equals_2_label.setGeometry(QtCore.QRect(1420, 280, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_equals_2_label.setFont(font)
        self.det2_equals_2_label.setObjectName("det2_equals_2_label")
        self.main_det_equals_1 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_equals_1.setGeometry(QtCore.QRect(290, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_equals_1.setFont(font)
        self.main_det_equals_1.setObjectName("main_det_equals_1")
        self.det2_equals_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_equals_1_label.setGeometry(QtCore.QRect(1070, 280, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_equals_1_label.setFont(font)
        self.det2_equals_1_label.setObjectName("det2_equals_1_label")
        self.det1_equals_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_equals_1_label.setGeometry(QtCore.QRect(290, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_equals_1_label.setFont(font)
        self.det1_equals_1_label.setObjectName("det1_equals_1_label")
        self.det3_equals_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_equals_1_label.setGeometry(QtCore.QRect(1070, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_equals_1_label.setFont(font)
        self.det3_equals_1_label.setObjectName("det3_equals_1_label")
        self.det1_equals_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_equals_2_label.setGeometry(QtCore.QRect(640, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_equals_2_label.setFont(font)
        self.det1_equals_2_label.setObjectName("det1_equals_2_label")
        self.det3_equals_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_equals_2_label.setGeometry(QtCore.QRect(1420, 480, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_equals_2_label.setFont(font)
        self.det3_equals_2_label.setObjectName("det3_equals_2_label")
        self.main_det_arg_33 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_33.setGeometry(QtCore.QRect(540, 350, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_33.setFont(font)
        self.main_det_arg_33.setText("")
        self.main_det_arg_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_det_arg_33.setObjectName("main_det_arg_33")
        self.main_det_arg_32 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_32.setGeometry(QtCore.QRect(440, 350, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_32.setFont(font)
        self.main_det_arg_32.setText("")
        self.main_det_arg_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_det_arg_32.setObjectName("main_det_arg_32")
        self.main_det_arg_21 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_21.setGeometry(QtCore.QRect(340, 300, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_21.setFont(font)
        self.main_det_arg_21.setText("")
        self.main_det_arg_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_det_arg_21.setObjectName("main_det_arg_21")
        self.main_det_arg_22 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_22.setGeometry(QtCore.QRect(440, 300, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_22.setFont(font)
        self.main_det_arg_22.setText("")
        self.main_det_arg_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_det_arg_22.setObjectName("main_det_arg_22")
        self.main_det_arg_12 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_12.setGeometry(QtCore.QRect(440, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_12.setFont(font)
        self.main_det_arg_12.setText("")
        self.main_det_arg_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_det_arg_12.setObjectName("main_det_arg_12")
        self.main_det_arg_13 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_13.setGeometry(QtCore.QRect(540, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_13.setFont(font)
        self.main_det_arg_13.setText("")
        self.main_det_arg_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_det_arg_13.setObjectName("main_det_arg_13")
        self.main_det_arg_31 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_31.setGeometry(QtCore.QRect(340, 350, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_31.setFont(font)
        self.main_det_arg_31.setText("")
        self.main_det_arg_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_det_arg_31.setObjectName("main_det_arg_31")
        self.main_det_arg_23 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_23.setGeometry(QtCore.QRect(540, 300, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_23.setFont(font)
        self.main_det_arg_23.setText("")
        self.main_det_arg_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_det_arg_23.setObjectName("main_det_arg_23")
        self.main_det_arg_11 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_11.setGeometry(QtCore.QRect(340, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_11.setFont(font)
        self.main_det_arg_11.setText("")
        self.main_det_arg_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main_det_arg_11.setObjectName("main_det_arg_11")
        self.x1_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_label.setGeometry(QtCore.QRect(190, 660, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_label.setFont(font)
        self.x1_label.setObjectName("x1_label")
        self.x2_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_label.setGeometry(QtCore.QRect(710, 660, 31, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_label.setFont(font)
        self.x2_label.setObjectName("x2_label")
        self.x3_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_label.setGeometry(QtCore.QRect(1300, 650, 21, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_label.setFont(font)
        self.x3_label.setObjectName("x3_label")
        self.x1_equals_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_equals_label.setGeometry(QtCore.QRect(210, 680, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_equals_label.setFont(font)
        self.x1_equals_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x1_equals_label.setObjectName("x1_equals_label")
        self.x2_equals_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_equals_label.setGeometry(QtCore.QRect(740, 680, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_equals_label.setFont(font)
        self.x2_equals_label.setObjectName("x2_equals_label")
        self.x3_equals_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_equals_label.setGeometry(QtCore.QRect(1320, 670, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_equals_label.setFont(font)
        self.x3_equals_label.setObjectName("x3_equals_label")
        self.x1_main_triangle_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_main_triangle_det_label.setGeometry(QtCore.QRect(260, 700, 51, 41))
        self.x1_main_triangle_det_label.setText("")
        self.x1_main_triangle_det_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x1_main_triangle_det_label.setObjectName("x1_main_triangle_det_label")
        self.x1_det1_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_det1_triangle_label.setGeometry(QtCore.QRect(260, 640, 51, 41))
        self.x1_det1_triangle_label.setText("")
        self.x1_det1_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x1_det1_triangle_label.setObjectName("x1_det1_triangle_label")
        self.x1_det_index_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_det_index_label.setGeometry(QtCore.QRect(310, 660, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.x1_det_index_label.setFont(font)
        self.x1_det_index_label.setObjectName("x1_det_index_label")
        self.x1_divide_line_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_divide_line_label.setGeometry(QtCore.QRect(250, 680, 81, 19))
        self.x1_divide_line_label.setText("")
        self.x1_divide_line_label.setPixmap(QtGui.QPixmap("line.jpg"))
        self.x1_divide_line_label.setObjectName("x1_divide_line_label")
        self.x2_divide_line_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_divide_line_label.setGeometry(QtCore.QRect(780, 690, 81, 19))
        self.x2_divide_line_label.setText("")
        self.x2_divide_line_label.setPixmap(QtGui.QPixmap("line.jpg"))
        self.x2_divide_line_label.setObjectName("x2_divide_line_label")
        self.x3_divide_line_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_divide_line_label.setGeometry(QtCore.QRect(1370, 680, 81, 19))
        self.x3_divide_line_label.setText("")
        self.x3_divide_line_label.setPixmap(QtGui.QPixmap("line.jpg"))
        self.x3_divide_line_label.setObjectName("x3_divide_line_label")
        self.x2_main_triangle_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_main_triangle_det_label.setGeometry(QtCore.QRect(790, 710, 51, 41))
        self.x2_main_triangle_det_label.setText("")
        self.x2_main_triangle_det_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x2_main_triangle_det_label.setObjectName("x2_main_triangle_det_label")
        self.x3_main_triangle_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_main_triangle_det_label.setGeometry(QtCore.QRect(1380, 700, 51, 41))
        self.x3_main_triangle_det_label.setText("")
        self.x3_main_triangle_det_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x3_main_triangle_det_label.setObjectName("x3_main_triangle_det_label")
        self.x2_det_index_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_det_index_label.setGeometry(QtCore.QRect(840, 670, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.x2_det_index_label.setFont(font)
        self.x2_det_index_label.setObjectName("x2_det_index_label")
        self.x2_det2_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_det2_triangle_label.setGeometry(QtCore.QRect(790, 650, 51, 41))
        self.x2_det2_triangle_label.setText("")
        self.x2_det2_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x2_det2_triangle_label.setObjectName("x2_det2_triangle_label")
        self.x3_det3_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_det3_triangle_label.setGeometry(QtCore.QRect(1380, 640, 51, 41))
        self.x3_det3_triangle_label.setText("")
        self.x3_det3_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x3_det3_triangle_label.setObjectName("x3_det3_triangle_label")
        self.x3_det_index_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_det_index_label.setGeometry(QtCore.QRect(1430, 670, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.x3_det_index_label.setFont(font)
        self.x3_det_index_label.setObjectName("x3_det_index_label")
        self.x1_equals2_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_equals2_label.setGeometry(QtCore.QRect(330, 680, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_equals2_label.setFont(font)
        self.x1_equals2_label.setObjectName("x1_equals2_label")
        self.x2_equals2_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_equals2_label.setGeometry(QtCore.QRect(870, 690, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_equals2_label.setFont(font)
        self.x2_equals2_label.setObjectName("x2_equals2_label")
        self.x1_divide_line2_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_divide_line2_label.setGeometry(QtCore.QRect(370, 680, 131, 19))
        self.x1_divide_line2_label.setText("")
        self.x1_divide_line2_label.setPixmap(QtGui.QPixmap("line.jpg"))
        self.x1_divide_line2_label.setObjectName("x1_divide_line2_label")
        self.x1_det1_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_det1_label.setGeometry(QtCore.QRect(370, 620, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_det1_label.setFont(font)
        self.x1_det1_label.setText("")
        self.x1_det1_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x1_det1_label.setObjectName("x1_det1_label")
        self.x3_equals2_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_equals2_label.setGeometry(QtCore.QRect(1460, 670, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_equals2_label.setFont(font)
        self.x3_equals2_label.setObjectName("x3_equals2_label")
        self.x1_main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_main_det_label.setGeometry(QtCore.QRect(370, 700, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_main_det_label.setFont(font)
        self.x1_main_det_label.setText("")
        self.x1_main_det_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x1_main_det_label.setObjectName("x1_main_det_label")
        self.x1_result_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_result_label.setGeometry(QtCore.QRect(540, 660, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_result_label.setFont(font)
        self.x1_result_label.setText("")
        self.x1_result_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.x1_result_label.setObjectName("x1_result_label")
        self.x1_equals3_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_equals3_label.setGeometry(QtCore.QRect(500, 680, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_equals3_label.setFont(font)
        self.x1_equals3_label.setObjectName("x1_equals3_label")
        self.x2_main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_main_det_label.setGeometry(QtCore.QRect(910, 710, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_main_det_label.setFont(font)
        self.x2_main_det_label.setText("")
        self.x2_main_det_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x2_main_det_label.setObjectName("x2_main_det_label")
        self.x2_divide_line2_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_divide_line2_label.setGeometry(QtCore.QRect(910, 690, 131, 19))
        self.x2_divide_line2_label.setText("")
        self.x2_divide_line2_label.setPixmap(QtGui.QPixmap("line.jpg"))
        self.x2_divide_line2_label.setObjectName("x2_divide_line2_label")
        self.x2_det2_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_det2_label.setGeometry(QtCore.QRect(910, 630, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_det2_label.setFont(font)
        self.x2_det2_label.setText("")
        self.x2_det2_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x2_det2_label.setObjectName("x2_det2_label")
        self.x2_equals3_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_equals3_label.setGeometry(QtCore.QRect(1040, 680, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_equals3_label.setFont(font)
        self.x2_equals3_label.setObjectName("x2_equals3_label")
        self.x2_result_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_result_label.setGeometry(QtCore.QRect(1080, 670, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_result_label.setFont(font)
        self.x2_result_label.setText("")
        self.x2_result_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.x2_result_label.setObjectName("x2_result_label")
        self.x3_main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_main_det_label.setGeometry(QtCore.QRect(1500, 700, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_main_det_label.setFont(font)
        self.x3_main_det_label.setText("")
        self.x3_main_det_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x3_main_det_label.setObjectName("x3_main_det_label")
        self.x3_equals3_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_equals3_label.setGeometry(QtCore.QRect(1630, 670, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_equals3_label.setFont(font)
        self.x3_equals3_label.setObjectName("x3_equals3_label")
        self.x3_det3_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_det3_label.setGeometry(QtCore.QRect(1500, 620, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_det3_label.setFont(font)
        self.x3_det3_label.setText("")
        self.x3_det3_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x3_det3_label.setObjectName("x3_det3_label")
        self.x3_result_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_result_label.setGeometry(QtCore.QRect(1670, 660, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_result_label.setFont(font)
        self.x3_result_label.setText("")
        self.x3_result_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.x3_result_label.setObjectName("x3_result_label")
        self.x3_divide_line2_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_divide_line2_label.setGeometry(QtCore.QRect(1500, 680, 131, 19))
        self.x3_divide_line2_label.setText("")
        self.x3_divide_line2_label.setPixmap(QtGui.QPixmap("line.jpg"))
        self.x3_divide_line2_label.setObjectName("x3_divide_line2_label")
        self.brace_label = QtWidgets.QLabel(self.centralwidget)
        self.brace_label.setGeometry(QtCore.QRect(250, 20, 41, 161))
        self.brace_label.setText("")
        self.brace_label.setPixmap(QtGui.QPixmap("brace.png"))
        self.brace_label.setObjectName("brace_label")
        self.x33_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x33_label_2.setGeometry(QtCore.QRect(670, 120, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x33_label_2.setFont(font)
        self.x33_label_2.setObjectName("x33_label_2")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(550, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(700, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(700, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.argument_label_21 = DragLabel(self.centralwidget)
        self.argument_label_21.setEnabled(True)
        self.argument_label_21.setGeometry(QtCore.QRect(280, 70, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_21.setFont(font)
        self.argument_label_21.setText("")
        self.argument_label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_21.setObjectName("argument_label_21")
        self.argument_label_12 = DragLabel(self.centralwidget)
        self.argument_label_12.setGeometry(QtCore.QRect(430, 20, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_12.setFont(font)
        self.argument_label_12.setText("")
        self.argument_label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_12.setObjectName("argument_label_12")
        self.argument_lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_11.setGeometry(QtCore.QRect(280, 30, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_11.setFont(font)
        self.argument_lineEdit_11.setObjectName("argument_lineEdit_11")
        self.x13_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x13_label_2.setGeometry(QtCore.QRect(370, 120, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x13_label_2.setFont(font)
        self.x13_label_2.setObjectName("x13_label_2")
        self.x32_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x32_label_2.setGeometry(QtCore.QRect(670, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x32_label_2.setFont(font)
        self.x32_label_2.setObjectName("x32_label_2")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(400, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.answer_label_2 = DragLabel(self.centralwidget)
        self.answer_label_2.setGeometry(QtCore.QRect(730, 70, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_2.setFont(font)
        self.answer_label_2.setText("")
        self.answer_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.answer_label_2.setObjectName("answer_label_2")
        self.argument_label_23 = DragLabel(self.centralwidget)
        self.argument_label_23.setGeometry(QtCore.QRect(580, 70, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_23.setFont(font)
        self.argument_label_23.setText("")
        self.argument_label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_23.setObjectName("argument_label_23")
        self.x12_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x12_label_2.setGeometry(QtCore.QRect(370, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x12_label_2.setFont(font)
        self.x12_label_2.setObjectName("x12_label_2")
        self.x21_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x21_label_2.setGeometry(QtCore.QRect(520, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x21_label_2.setFont(font)
        self.x21_label_2.setObjectName("x21_label_2")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(700, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(550, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.argument_label_31 = DragLabel(self.centralwidget)
        self.argument_label_31.setEnabled(True)
        self.argument_label_31.setGeometry(QtCore.QRect(280, 120, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_31.setFont(font)
        self.argument_label_31.setText("")
        self.argument_label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_31.setObjectName("argument_label_31")
        self.argument_label_22 = DragLabel(self.centralwidget)
        self.argument_label_22.setGeometry(QtCore.QRect(430, 70, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_22.setFont(font)
        self.argument_label_22.setText("")
        self.argument_label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_22.setObjectName("argument_label_22")
        self.argument_label_13 = DragLabel(self.centralwidget)
        self.argument_label_13.setGeometry(QtCore.QRect(580, 20, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_13.setFont(font)
        self.argument_label_13.setText("")
        self.argument_label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_13.setObjectName("argument_label_13")
        self.x31_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x31_label_2.setGeometry(QtCore.QRect(670, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x31_label_2.setFont(font)
        self.x31_label_2.setObjectName("x31_label_2")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(550, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.x11_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x11_label_2.setGeometry(QtCore.QRect(370, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x11_label_2.setFont(font)
        self.x11_label_2.setObjectName("x11_label_2")
        self.x23_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x23_label_2.setGeometry(QtCore.QRect(520, 120, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x23_label_2.setFont(font)
        self.x23_label_2.setObjectName("x23_label_2")
        self.answer_label_1 = DragLabel(self.centralwidget)
        self.answer_label_1.setGeometry(QtCore.QRect(730, 20, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_1.setFont(font)
        self.answer_label_1.setText("")
        self.answer_label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.answer_label_1.setObjectName("answer_label_1")
        self.x22_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x22_label_2.setGeometry(QtCore.QRect(520, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x22_label_2.setFont(font)
        self.x22_label_2.setObjectName("x22_label_2")
        self.argument_label_11 = DragLabel(self.centralwidget)
        self.argument_label_11.setEnabled(True)
        self.argument_label_11.setGeometry(QtCore.QRect(280, 20, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_11.setFont(font)
        self.argument_label_11.setText("")
        self.argument_label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_11.setObjectName("argument_label_11")
        self.answer_label_3 = DragLabel(self.centralwidget)
        self.answer_label_3.setGeometry(QtCore.QRect(730, 120, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_3.setFont(font)
        self.answer_label_3.setText("")
        self.answer_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.answer_label_3.setObjectName("answer_label_3")
        self.argument_label_33 = DragLabel(self.centralwidget)
        self.argument_label_33.setGeometry(QtCore.QRect(580, 120, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_33.setFont(font)
        self.argument_label_33.setText("")
        self.argument_label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_33.setObjectName("argument_label_33")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(400, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.argument_label_32 = DragLabel(self.centralwidget)
        self.argument_label_32.setGeometry(QtCore.QRect(430, 120, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_32.setFont(font)
        self.argument_label_32.setText("")
        self.argument_label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_32.setObjectName("argument_label_32")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(400, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.argument_lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_12.setGeometry(QtCore.QRect(430, 30, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_12.setFont(font)
        self.argument_lineEdit_12.setObjectName("argument_lineEdit_12")
        self.argument_lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_13.setGeometry(QtCore.QRect(580, 30, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_13.setFont(font)
        self.argument_lineEdit_13.setObjectName("argument_lineEdit_13")
        self.answer_LineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_LineEdit_1.setGeometry(QtCore.QRect(740, 30, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_LineEdit_1.setFont(font)
        self.answer_LineEdit_1.setObjectName("answer_LineEdit_1")
        self.argument_lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_21.setGeometry(QtCore.QRect(280, 80, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_21.setFont(font)
        self.argument_lineEdit_21.setObjectName("argument_lineEdit_21")
        self.argument_lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_22.setGeometry(QtCore.QRect(430, 80, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_22.setFont(font)
        self.argument_lineEdit_22.setObjectName("argument_lineEdit_22")
        self.argument_lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_23.setGeometry(QtCore.QRect(580, 80, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_23.setFont(font)
        self.argument_lineEdit_23.setObjectName("argument_lineEdit_23")
        self.answer_LineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_LineEdit_2.setGeometry(QtCore.QRect(740, 80, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_LineEdit_2.setFont(font)
        self.answer_LineEdit_2.setObjectName("answer_LineEdit_2")
        self.argument_lineEdit_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_31.setGeometry(QtCore.QRect(280, 130, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_31.setFont(font)
        self.argument_lineEdit_31.setObjectName("argument_lineEdit_31")
        self.argument_lineEdit_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_32.setGeometry(QtCore.QRect(430, 130, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_32.setFont(font)
        self.argument_lineEdit_32.setObjectName("argument_lineEdit_32")
        self.argument_lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_33.setGeometry(QtCore.QRect(580, 130, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_33.setFont(font)
        self.argument_lineEdit_33.setObjectName("argument_lineEdit_33")
        self.answer_LineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_LineEdit_3.setGeometry(QtCore.QRect(740, 130, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_LineEdit_3.setFont(font)
        self.answer_LineEdit_3.setObjectName("answer_LineEdit_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "next"))
        self.main_det_equals_2.setText(_translate("MainWindow", "="))
        self.det1_index_label.setText(_translate("MainWindow", "1"))
        self.det2_index_label.setText(_translate("MainWindow", "2"))
        self.det3_index_label.setText(_translate("MainWindow", "3"))
        self.det2_equals_2_label.setText(_translate("MainWindow", "="))
        self.main_det_equals_1.setText(_translate("MainWindow", "="))
        self.det2_equals_1_label.setText(_translate("MainWindow", "="))
        self.det1_equals_1_label.setText(_translate("MainWindow", "="))
        self.det3_equals_1_label.setText(_translate("MainWindow", "="))
        self.det1_equals_2_label.setText(_translate("MainWindow", "="))
        self.det3_equals_2_label.setText(_translate("MainWindow", "="))
        self.x1_label.setText(_translate("MainWindow", "x"))
        self.x2_label.setText(_translate("MainWindow", "y"))
        self.x3_label.setText(_translate("MainWindow", "z"))
        self.x1_equals_label.setText(_translate("MainWindow", "="))
        self.x2_equals_label.setText(_translate("MainWindow", "="))
        self.x3_equals_label.setText(_translate("MainWindow", "="))
        self.x1_det_index_label.setText(_translate("MainWindow", "1"))
        self.x2_det_index_label.setText(_translate("MainWindow", "2"))
        self.x3_det_index_label.setText(_translate("MainWindow", "3"))
        self.x1_equals2_label.setText(_translate("MainWindow", "="))
        self.x2_equals2_label.setText(_translate("MainWindow", "="))
        self.x3_equals2_label.setText(_translate("MainWindow", "="))
        self.x1_equals3_label.setText(_translate("MainWindow", "="))
        self.x2_equals3_label.setText(_translate("MainWindow", "="))
        self.x3_equals3_label.setText(_translate("MainWindow", "="))
        self.x33_label_2.setText(_translate("MainWindow", "z"))
        self.label_14.setText(_translate("MainWindow", "+"))
        self.label_25.setText(_translate("MainWindow", "="))
        self.label_17.setText(_translate("MainWindow", "="))
        self.x13_label_2.setText(_translate("MainWindow", "x"))
        self.x32_label_2.setText(_translate("MainWindow", "z"))
        self.label_20.setText(_translate("MainWindow", "+"))
        self.x12_label_2.setText(_translate("MainWindow", "x"))
        self.x21_label_2.setText(_translate("MainWindow", "y"))
        self.label_23.setText(_translate("MainWindow", "="))
        self.label_15.setText(_translate("MainWindow", "+"))
        self.x31_label_2.setText(_translate("MainWindow", "z"))
        self.label_26.setText(_translate("MainWindow", "+"))
        self.x11_label_2.setText(_translate("MainWindow", "x"))
        self.x23_label_2.setText(_translate("MainWindow", "y"))
        self.x22_label_2.setText(_translate("MainWindow", "y"))
        self.label_24.setText(_translate("MainWindow", "+"))
        self.label_18.setText(_translate("MainWindow", "+"))
