# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_gauss.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from dragLabel import DragLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1545, 972)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.brace_label = QtWidgets.QLabel(self.centralwidget)
        self.brace_label.setGeometry(QtCore.QRect(180, 20, 41, 161))
        self.brace_label.setText("")
        self.brace_label.setPixmap(QtGui.QPixmap("brace.png"))
        self.brace_label.setObjectName("brace_label")
        self.matrixA_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrixA_bracket_label_1.setGeometry(QtCore.QRect(120, 200, 61, 171))
        self.matrixA_bracket_label_1.setText("")
        self.matrixA_bracket_label_1.setPixmap(QtGui.QPixmap("skobka1.png"))
        self.matrixA_bracket_label_1.setObjectName("matrixA_bracket_label_1")
        self.matrixA_label_11 = DragLabel(self.centralwidget)
        self.matrixA_label_11.setGeometry(QtCore.QRect(160, 210, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_11.setFont(font)
        self.matrixA_label_11.setText("")
        self.matrixA_label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_11.setObjectName("matrixA_label_11")
        self.matrixA_label_21 = DragLabel(self.centralwidget)
        self.matrixA_label_21.setGeometry(QtCore.QRect(160, 260, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_21.setFont(font)
        self.matrixA_label_21.setText("")
        self.matrixA_label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_21.setObjectName("matrixA_label_21")
        self.matrixA_label_31 = DragLabel(self.centralwidget)
        self.matrixA_label_31.setGeometry(QtCore.QRect(160, 310, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_31.setFont(font)
        self.matrixA_label_31.setText("")
        self.matrixA_label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_31.setObjectName("matrixA_label_31")
        self.matrixA_label_12 = DragLabel(self.centralwidget)
        self.matrixA_label_12.setGeometry(QtCore.QRect(260, 210, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_12.setFont(font)
        self.matrixA_label_12.setText("")
        self.matrixA_label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_12.setObjectName("matrixA_label_12")
        self.matrixA_label_32 = DragLabel(self.centralwidget)
        self.matrixA_label_32.setGeometry(QtCore.QRect(260, 310, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_32.setFont(font)
        self.matrixA_label_32.setText("")
        self.matrixA_label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_32.setObjectName("matrixA_label_32")
        self.matrixA_label_22 = DragLabel(self.centralwidget)
        self.matrixA_label_22.setGeometry(QtCore.QRect(260, 260, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_22.setFont(font)
        self.matrixA_label_22.setText("")
        self.matrixA_label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_22.setObjectName("matrixA_label_22")
        self.matrixA_label_13 = DragLabel(self.centralwidget)
        self.matrixA_label_13.setGeometry(QtCore.QRect(360, 210, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_13.setFont(font)
        self.matrixA_label_13.setText("")
        self.matrixA_label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_13.setObjectName("matrixA_label_13")
        self.matrixA_label_33 = DragLabel(self.centralwidget)
        self.matrixA_label_33.setGeometry(QtCore.QRect(360, 310, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_33.setFont(font)
        self.matrixA_label_33.setText("")
        self.matrixA_label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_33.setObjectName("matrixA_label_33")
        self.matrixA_label_23 = DragLabel(self.centralwidget)
        self.matrixA_label_23.setGeometry(QtCore.QRect(360, 260, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_23.setFont(font)
        self.matrixA_label_23.setText("")
        self.matrixA_label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_23.setObjectName("matrixA_label_23")
        self.matrixA_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrixA_bracket_label_2.setGeometry(QtCore.QRect(450, 200, 51, 171))
        self.matrixA_bracket_label_2.setText("")
        self.matrixA_bracket_label_2.setPixmap(QtGui.QPixmap("skobka2.png"))
        self.matrixA_bracket_label_2.setObjectName("matrixA_bracket_label_2")
        self.matrixB_1 = DragLabel(self.centralwidget)
        self.matrixB_1.setGeometry(QtCore.QRect(640, 210, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixB_1.setFont(font)
        self.matrixB_1.setText("")
        self.matrixB_1.setAlignment(QtCore.Qt.AlignCenter)
        self.matrixB_1.setObjectName("matrixB_1")
        self.matrixB_3 = DragLabel(self.centralwidget)
        self.matrixB_3.setGeometry(QtCore.QRect(640, 310, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixB_3.setFont(font)
        self.matrixB_3.setText("")
        self.matrixB_3.setAlignment(QtCore.Qt.AlignCenter)
        self.matrixB_3.setObjectName("matrixB_3")
        self.matrixB_2 = DragLabel(self.centralwidget)
        self.matrixB_2.setGeometry(QtCore.QRect(640, 260, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixB_2.setFont(font)
        self.matrixB_2.setText("")
        self.matrixB_2.setAlignment(QtCore.Qt.AlignCenter)
        self.matrixB_2.setObjectName("matrixB_2")
        self.matrixB_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrixB_bracket_label_1.setGeometry(QtCore.QRect(600, 200, 51, 171))
        self.matrixB_bracket_label_1.setText("")
        self.matrixB_bracket_label_1.setPixmap(QtGui.QPixmap("skobka1.png"))
        self.matrixB_bracket_label_1.setObjectName("matrixB_bracket_label_1")
        self.matrixB_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrixB_bracket_label_2.setGeometry(QtCore.QRect(710, 200, 51, 171))
        self.matrixB_bracket_label_2.setText("")
        self.matrixB_bracket_label_2.setPixmap(QtGui.QPixmap("skobka2.png"))
        self.matrixB_bracket_label_2.setObjectName("matrixB_bracket_label_2")
        self.matrixA_label = QtWidgets.QLabel(self.centralwidget)
        self.matrixA_label.setGeometry(QtCore.QRect(40, 260, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label.setFont(font)
        self.matrixA_label.setObjectName("matrixA_label")
        self.matrixB_label = QtWidgets.QLabel(self.centralwidget)
        self.matrixB_label.setGeometry(QtCore.QRect(530, 260, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrixB_label.setFont(font)
        self.matrixB_label.setObjectName("matrixB_label")
        self.matrix1_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrix1_bracket_label_1.setGeometry(QtCore.QRect(0, 400, 61, 171))
        self.matrix1_bracket_label_1.setText("")
        self.matrix1_bracket_label_1.setPixmap(QtGui.QPixmap("skobka1.png"))
        self.matrix1_bracket_label_1.setObjectName("matrix1_bracket_label_1")
        self.matrix_1_31 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_31.setGeometry(QtCore.QRect(40, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_31.setFont(font)
        self.matrix_1_31.setText("")
        self.matrix_1_31.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_31.setObjectName("matrix_1_31")
        self.matrix_1_23 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_23.setGeometry(QtCore.QRect(240, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_23.setFont(font)
        self.matrix_1_23.setText("")
        self.matrix_1_23.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_23.setObjectName("matrix_1_23")
        self.matrix_1_11 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_11.setGeometry(QtCore.QRect(40, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_11.setFont(font)
        self.matrix_1_11.setText("")
        self.matrix_1_11.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_11.setObjectName("matrix_1_11")
        self.matrix_1_22 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_22.setGeometry(QtCore.QRect(140, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_22.setFont(font)
        self.matrix_1_22.setText("")
        self.matrix_1_22.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_22.setObjectName("matrix_1_22")
        self.matrix_1_32 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_32.setGeometry(QtCore.QRect(140, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_32.setFont(font)
        self.matrix_1_32.setText("")
        self.matrix_1_32.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_32.setObjectName("matrix_1_32")
        self.matrix_1_33 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_33.setGeometry(QtCore.QRect(240, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_33.setFont(font)
        self.matrix_1_33.setText("")
        self.matrix_1_33.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_33.setObjectName("matrix_1_33")
        self.matrix_1_12 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_12.setGeometry(QtCore.QRect(140, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_12.setFont(font)
        self.matrix_1_12.setText("")
        self.matrix_1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_12.setObjectName("matrix_1_12")
        self.matrix_1_13 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_13.setGeometry(QtCore.QRect(240, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_13.setFont(font)
        self.matrix_1_13.setText("")
        self.matrix_1_13.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_13.setObjectName("matrix_1_13")
        self.matrix_1_21 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_21.setGeometry(QtCore.QRect(40, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_21.setFont(font)
        self.matrix_1_21.setText("")
        self.matrix_1_21.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_21.setObjectName("matrix_1_21")
        self.matrix1_vertLine_label = QtWidgets.QLabel(self.centralwidget)
        self.matrix1_vertLine_label.setGeometry(QtCore.QRect(343, 405, 21, 161))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix1_vertLine_label.setFont(font)
        self.matrix1_vertLine_label.setText("")
        self.matrix1_vertLine_label.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.matrix1_vertLine_label.setObjectName("matrix1_vertLine_label")
        self.matrix_1_14 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_14.setGeometry(QtCore.QRect(350, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_14.setFont(font)
        self.matrix_1_14.setText("")
        self.matrix_1_14.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_14.setObjectName("matrix_1_14")
        self.matrix_1_24 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_24.setGeometry(QtCore.QRect(350, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_24.setFont(font)
        self.matrix_1_24.setText("")
        self.matrix_1_24.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_24.setObjectName("matrix_1_24")
        self.matrix_1_34 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_34.setGeometry(QtCore.QRect(350, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_34.setFont(font)
        self.matrix_1_34.setText("")
        self.matrix_1_34.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_34.setObjectName("matrix_1_34")
        self.matrix1_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrix1_bracket_label_2.setGeometry(QtCore.QRect(430, 400, 51, 171))
        self.matrix1_bracket_label_2.setText("")
        self.matrix1_bracket_label_2.setPixmap(QtGui.QPixmap("skobka2.png"))
        self.matrix1_bracket_label_2.setObjectName("matrix1_bracket_label_2")
        self.tilde_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.tilde_label_1.setGeometry(QtCore.QRect(480, 460, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(55)
        font.setBold(True)
        font.setWeight(75)
        self.tilde_label_1.setFont(font)
        self.tilde_label_1.setObjectName("tilde_label_1")
        self.matrix_2_11 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_11.setGeometry(QtCore.QRect(560, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_11.setFont(font)
        self.matrix_2_11.setText("")
        self.matrix_2_11.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_11.setObjectName("matrix_2_11")
        self.matrix_2_32 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_32.setGeometry(QtCore.QRect(660, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_32.setFont(font)
        self.matrix_2_32.setText("")
        self.matrix_2_32.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_32.setObjectName("matrix_2_32")
        self.matrix_2_34 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_34.setGeometry(QtCore.QRect(870, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_34.setFont(font)
        self.matrix_2_34.setText("")
        self.matrix_2_34.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_34.setObjectName("matrix_2_34")
        self.matrix_2_33 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_33.setGeometry(QtCore.QRect(760, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_33.setFont(font)
        self.matrix_2_33.setText("")
        self.matrix_2_33.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_33.setObjectName("matrix_2_33")
        self.matrix_2_21 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_21.setGeometry(QtCore.QRect(560, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_21.setFont(font)
        self.matrix_2_21.setText("")
        self.matrix_2_21.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_21.setObjectName("matrix_2_21")
        self.matrix_2_23 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_23.setGeometry(QtCore.QRect(760, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_23.setFont(font)
        self.matrix_2_23.setText("")
        self.matrix_2_23.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_23.setObjectName("matrix_2_23")
        self.matrix_2_12 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_12.setGeometry(QtCore.QRect(660, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_12.setFont(font)
        self.matrix_2_12.setText("")
        self.matrix_2_12.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_12.setObjectName("matrix_2_12")
        self.matrix_2_13 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_13.setGeometry(QtCore.QRect(760, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_13.setFont(font)
        self.matrix_2_13.setText("")
        self.matrix_2_13.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_13.setObjectName("matrix_2_13")
        self.matrix_2_31 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_31.setGeometry(QtCore.QRect(560, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_31.setFont(font)
        self.matrix_2_31.setText("")
        self.matrix_2_31.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_31.setObjectName("matrix_2_31")
        self.matrix2_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrix2_bracket_label_1.setGeometry(QtCore.QRect(522, 400, 61, 171))
        self.matrix2_bracket_label_1.setText("")
        self.matrix2_bracket_label_1.setPixmap(QtGui.QPixmap("skobka1.png"))
        self.matrix2_bracket_label_1.setObjectName("matrix2_bracket_label_1")
        self.matrix_2_24 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_24.setGeometry(QtCore.QRect(870, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_24.setFont(font)
        self.matrix_2_24.setText("")
        self.matrix_2_24.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_24.setObjectName("matrix_2_24")
        self.matrix_2_14 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_14.setGeometry(QtCore.QRect(870, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_14.setFont(font)
        self.matrix_2_14.setText("")
        self.matrix_2_14.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_14.setObjectName("matrix_2_14")
        self.matrix2_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrix2_bracket_label_2.setGeometry(QtCore.QRect(950, 400, 51, 171))
        self.matrix2_bracket_label_2.setText("")
        self.matrix2_bracket_label_2.setPixmap(QtGui.QPixmap("skobka2.png"))
        self.matrix2_bracket_label_2.setObjectName("matrix2_bracket_label_2")
        self.matrix_2_22 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_22.setGeometry(QtCore.QRect(660, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_22.setFont(font)
        self.matrix_2_22.setText("")
        self.matrix_2_22.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_22.setObjectName("matrix_2_22")
        self.matrix_3_21 = DragLabel(self.centralwidget)
        self.matrix_3_21.setGeometry(QtCore.QRect(1080, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_21.setFont(font)
        self.matrix_3_21.setText("")
        self.matrix_3_21.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_21.setObjectName("matrix_3_21")
        self.matrix_3_31 = DragLabel(self.centralwidget)
        self.matrix_3_31.setGeometry(QtCore.QRect(1080, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_31.setFont(font)
        self.matrix_3_31.setText("")
        self.matrix_3_31.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_31.setObjectName("matrix_3_31")
        self.matrix3_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrix3_bracket_label_1.setGeometry(QtCore.QRect(1040, 400, 61, 171))
        self.matrix3_bracket_label_1.setText("")
        self.matrix3_bracket_label_1.setPixmap(QtGui.QPixmap("skobka1.png"))
        self.matrix3_bracket_label_1.setObjectName("matrix3_bracket_label_1")
        self.matrix_3_34 = DragLabel(self.centralwidget)
        self.matrix_3_34.setGeometry(QtCore.QRect(1390, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_34.setFont(font)
        self.matrix_3_34.setText("")
        self.matrix_3_34.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_34.setObjectName("matrix_3_34")
        self.matrix_3_33 = DragLabel(self.centralwidget)
        self.matrix_3_33.setGeometry(QtCore.QRect(1280, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_33.setFont(font)
        self.matrix_3_33.setText("")
        self.matrix_3_33.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_33.setObjectName("matrix_3_33")
        self.matrix_3_11 = DragLabel(self.centralwidget)
        self.matrix_3_11.setGeometry(QtCore.QRect(1080, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_11.setFont(font)
        self.matrix_3_11.setText("")
        self.matrix_3_11.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_11.setObjectName("matrix_3_11")
        self.matrix_3_32 = DragLabel(self.centralwidget)
        self.matrix_3_32.setGeometry(QtCore.QRect(1180, 510, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_32.setFont(font)
        self.matrix_3_32.setText("")
        self.matrix_3_32.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_32.setObjectName("matrix_3_32")
        self.matrix_3_23 = DragLabel(self.centralwidget)
        self.matrix_3_23.setGeometry(QtCore.QRect(1280, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_23.setFont(font)
        self.matrix_3_23.setText("")
        self.matrix_3_23.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_23.setObjectName("matrix_3_23")
        self.matrix3_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrix3_bracket_label_2.setGeometry(QtCore.QRect(1470, 400, 51, 171))
        self.matrix3_bracket_label_2.setText("")
        self.matrix3_bracket_label_2.setPixmap(QtGui.QPixmap("skobka2.png"))
        self.matrix3_bracket_label_2.setObjectName("matrix3_bracket_label_2")
        self.tilde_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.tilde_label_2.setGeometry(QtCore.QRect(1000, 460, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(55)
        font.setBold(True)
        font.setWeight(75)
        self.tilde_label_2.setFont(font)
        self.tilde_label_2.setObjectName("tilde_label_2")
        self.matrix_3_13 = DragLabel(self.centralwidget)
        self.matrix_3_13.setGeometry(QtCore.QRect(1280, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_13.setFont(font)
        self.matrix_3_13.setText("")
        self.matrix_3_13.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_13.setObjectName("matrix_3_13")
        self.matrix_3_14 = DragLabel(self.centralwidget)
        self.matrix_3_14.setGeometry(QtCore.QRect(1390, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_14.setFont(font)
        self.matrix_3_14.setText("")
        self.matrix_3_14.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_14.setObjectName("matrix_3_14")
        self.matrix_3_22 = DragLabel(self.centralwidget)
        self.matrix_3_22.setGeometry(QtCore.QRect(1180, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_22.setFont(font)
        self.matrix_3_22.setText("")
        self.matrix_3_22.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_22.setObjectName("matrix_3_22")
        self.matrix_3_12 = DragLabel(self.centralwidget)
        self.matrix_3_12.setGeometry(QtCore.QRect(1180, 410, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_12.setFont(font)
        self.matrix_3_12.setText("")
        self.matrix_3_12.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_12.setObjectName("matrix_3_12")
        self.matrix_3_24 = DragLabel(self.centralwidget)
        self.matrix_3_24.setGeometry(QtCore.QRect(1390, 460, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_24.setFont(font)
        self.matrix_3_24.setText("")
        self.matrix_3_24.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_24.setObjectName("matrix_3_24")
        self.matrix2_vertLine_label = QtWidgets.QLabel(self.centralwidget)
        self.matrix2_vertLine_label.setGeometry(QtCore.QRect(862, 405, 21, 161))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix2_vertLine_label.setFont(font)
        self.matrix2_vertLine_label.setText("")
        self.matrix2_vertLine_label.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.matrix2_vertLine_label.setObjectName("matrix2_vertLine_label")
        self.matrix3_vertLine_label = QtWidgets.QLabel(self.centralwidget)
        self.matrix3_vertLine_label.setGeometry(QtCore.QRect(1382, 405, 21, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix3_vertLine_label.setFont(font)
        self.matrix3_vertLine_label.setText("")
        self.matrix3_vertLine_label.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.matrix3_vertLine_label.setObjectName("matrix3_vertLine_label")
        self.augmentMatrix_label_33 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_33.setGeometry(QtCore.QRect(1090, 310, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_33.setFont(font)
        self.augmentMatrix_label_33.setText("")
        self.augmentMatrix_label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_33.setObjectName("augmentMatrix_label_33")
        self.augmentMatrix_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_bracket_label_1.setGeometry(QtCore.QRect(850, 200, 61, 171))
        self.augmentMatrix_bracket_label_1.setText("")
        self.augmentMatrix_bracket_label_1.setPixmap(QtGui.QPixmap("skobka1.png"))
        self.augmentMatrix_bracket_label_1.setObjectName("augmentMatrix_bracket_label_1")
        self.augmentMatrix_label_11 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_11.setGeometry(QtCore.QRect(890, 210, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_11.setFont(font)
        self.augmentMatrix_label_11.setText("")
        self.augmentMatrix_label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_11.setObjectName("augmentMatrix_label_11")
        self.augmentMatrix_label_21 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_21.setGeometry(QtCore.QRect(890, 260, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_21.setFont(font)
        self.augmentMatrix_label_21.setText("")
        self.augmentMatrix_label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_21.setObjectName("augmentMatrix_label_21")
        self.augmentMatrix_label_22 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_22.setGeometry(QtCore.QRect(990, 260, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_22.setFont(font)
        self.augmentMatrix_label_22.setText("")
        self.augmentMatrix_label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_22.setObjectName("augmentMatrix_label_22")
        self.augmentMatrix_label_24 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_24.setGeometry(QtCore.QRect(1190, 260, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_24.setFont(font)
        self.augmentMatrix_label_24.setText("")
        self.augmentMatrix_label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_24.setObjectName("augmentMatrix_label_24")
        self.augmentMatrix_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_bracket_label_2.setGeometry(QtCore.QRect(1260, 200, 51, 171))
        self.augmentMatrix_bracket_label_2.setText("")
        self.augmentMatrix_bracket_label_2.setPixmap(QtGui.QPixmap("skobka2.png"))
        self.augmentMatrix_bracket_label_2.setObjectName("augmentMatrix_bracket_label_2")
        self.augmentMatrix_label_34 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_34.setGeometry(QtCore.QRect(1190, 310, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_34.setFont(font)
        self.augmentMatrix_label_34.setText("")
        self.augmentMatrix_label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_34.setObjectName("augmentMatrix_label_34")
        self.augmentMatrix_label_13 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_13.setGeometry(QtCore.QRect(1090, 210, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_13.setFont(font)
        self.augmentMatrix_label_13.setText("")
        self.augmentMatrix_label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_13.setObjectName("augmentMatrix_label_13")
        self.augmentMatrix_label_32 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_32.setGeometry(QtCore.QRect(990, 310, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_32.setFont(font)
        self.augmentMatrix_label_32.setText("")
        self.augmentMatrix_label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_32.setObjectName("augmentMatrix_label_32")
        self.augmentMatrix_label_31 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_31.setGeometry(QtCore.QRect(890, 310, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_31.setFont(font)
        self.augmentMatrix_label_31.setText("")
        self.augmentMatrix_label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_31.setObjectName("augmentMatrix_label_31")
        self.augmentMatrix_label_12 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_12.setGeometry(QtCore.QRect(990, 210, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_12.setFont(font)
        self.augmentMatrix_label_12.setText("")
        self.augmentMatrix_label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_12.setObjectName("augmentMatrix_label_12")
        self.augmentMatrix_label_14 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_14.setGeometry(QtCore.QRect(1190, 210, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_14.setFont(font)
        self.augmentMatrix_label_14.setText("")
        self.augmentMatrix_label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_14.setObjectName("augmentMatrix_label_14")
        self.augmentMatrix_label_23 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_23.setGeometry(QtCore.QRect(1090, 260, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_23.setFont(font)
        self.augmentMatrix_label_23.setText("")
        self.augmentMatrix_label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_23.setObjectName("augmentMatrix_label_23")
        self.augmentMatrix_vertLine_label = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_vertLine_label.setGeometry(QtCore.QRect(1180, 200, 21, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_vertLine_label.setFont(font)
        self.augmentMatrix_vertLine_label.setText("")
        self.augmentMatrix_vertLine_label.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.augmentMatrix_vertLine_label.setObjectName("augmentMatrix_vertLine_label")
        self.x11_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x11_label_2.setGeometry(QtCore.QRect(300, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x11_label_2.setFont(font)
        self.x11_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x11_label_2.setObjectName("x11_label_2")
        self.x22_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x22_label_2.setGeometry(QtCore.QRect(450, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x22_label_2.setFont(font)
        self.x22_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x22_label_2.setObjectName("x22_label_2")
        self.x13_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x13_label_2.setGeometry(QtCore.QRect(300, 120, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x13_label_2.setFont(font)
        self.x13_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x13_label_2.setObjectName("x13_label_2")
        self.argument_label_13 = DragLabel(self.centralwidget)
        self.argument_label_13.setGeometry(QtCore.QRect(510, 20, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_13.setFont(font)
        self.argument_label_13.setText("")
        self.argument_label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_13.setObjectName("argument_label_13")
        self.x31_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x31_label_2.setGeometry(QtCore.QRect(600, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x31_label_2.setFont(font)
        self.x31_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x31_label_2.setObjectName("x31_label_2")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(330, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.answer_label_1 = DragLabel(self.centralwidget)
        self.answer_label_1.setGeometry(QtCore.QRect(660, 20, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_1.setFont(font)
        self.answer_label_1.setText("")
        self.answer_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_label_1.setObjectName("answer_label_1")
        self.argument_label_21 = DragLabel(self.centralwidget)
        self.argument_label_21.setEnabled(True)
        self.argument_label_21.setGeometry(QtCore.QRect(210, 70, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_21.setFont(font)
        self.argument_label_21.setText("")
        self.argument_label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_21.setObjectName("argument_label_21")
        self.x32_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x32_label_2.setGeometry(QtCore.QRect(600, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x32_label_2.setFont(font)
        self.x32_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x32_label_2.setObjectName("x32_label_2")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(630, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(480, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.answer_label_3 = DragLabel(self.centralwidget)
        self.answer_label_3.setGeometry(QtCore.QRect(660, 120, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_3.setFont(font)
        self.answer_label_3.setText("")
        self.answer_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_label_3.setObjectName("answer_label_3")
        self.argument_label_33 = DragLabel(self.centralwidget)
        self.argument_label_33.setGeometry(QtCore.QRect(510, 120, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_33.setFont(font)
        self.argument_label_33.setText("")
        self.argument_label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_33.setObjectName("argument_label_33")
        self.argument_label_32 = DragLabel(self.centralwidget)
        self.argument_label_32.setGeometry(QtCore.QRect(360, 120, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_32.setFont(font)
        self.argument_label_32.setText("")
        self.argument_label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_32.setObjectName("argument_label_32")
        self.x12_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x12_label_2.setGeometry(QtCore.QRect(300, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x12_label_2.setFont(font)
        self.x12_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x12_label_2.setObjectName("x12_label_2")
        self.argument_label_11 = DragLabel(self.centralwidget)
        self.argument_label_11.setEnabled(True)
        self.argument_label_11.setGeometry(QtCore.QRect(210, 20, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_11.setFont(font)
        self.argument_label_11.setText("")
        self.argument_label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_11.setObjectName("argument_label_11")
        self.argument_lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_11.setGeometry(QtCore.QRect(210, 30, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_11.setFont(font)
        self.argument_lineEdit_11.setObjectName("argument_lineEdit_11")
        self.x21_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x21_label_2.setGeometry(QtCore.QRect(450, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x21_label_2.setFont(font)
        self.x21_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x21_label_2.setObjectName("x21_label_2")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(630, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(480, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.argument_label_22 = DragLabel(self.centralwidget)
        self.argument_label_22.setGeometry(QtCore.QRect(360, 70, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_22.setFont(font)
        self.argument_label_22.setText("")
        self.argument_label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_22.setObjectName("argument_label_22")
        self.answer_label_2 = DragLabel(self.centralwidget)
        self.answer_label_2.setGeometry(QtCore.QRect(660, 70, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_2.setFont(font)
        self.answer_label_2.setText("")
        self.answer_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_label_2.setObjectName("answer_label_2")
        self.argument_label_12 = DragLabel(self.centralwidget)
        self.argument_label_12.setGeometry(QtCore.QRect(360, 20, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_12.setFont(font)
        self.argument_label_12.setText("")
        self.argument_label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_12.setObjectName("argument_label_12")
        self.argument_label_31 = DragLabel(self.centralwidget)
        self.argument_label_31.setEnabled(True)
        self.argument_label_31.setGeometry(QtCore.QRect(210, 120, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_31.setFont(font)
        self.argument_label_31.setText("")
        self.argument_label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_31.setObjectName("argument_label_31")
        self.argument_label_23 = DragLabel(self.centralwidget)
        self.argument_label_23.setGeometry(QtCore.QRect(510, 70, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_23.setFont(font)
        self.argument_label_23.setText("")
        self.argument_label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_23.setObjectName("argument_label_23")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(330, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.x33_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x33_label_2.setGeometry(QtCore.QRect(600, 120, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x33_label_2.setFont(font)
        self.x33_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x33_label_2.setObjectName("x33_label_2")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(330, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(630, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.x23_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x23_label_2.setGeometry(QtCore.QRect(450, 120, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x23_label_2.setFont(font)
        self.x23_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x23_label_2.setObjectName("x23_label_2")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(480, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.argument_lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_12.setGeometry(QtCore.QRect(360, 30, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_12.setFont(font)
        self.argument_lineEdit_12.setObjectName("argument_lineEdit_12")
        self.argument_lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_13.setGeometry(QtCore.QRect(510, 30, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_13.setFont(font)
        self.argument_lineEdit_13.setObjectName("argument_lineEdit_13")
        self.answer_lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_lineEdit_1.setGeometry(QtCore.QRect(670, 30, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_lineEdit_1.setFont(font)
        self.answer_lineEdit_1.setObjectName("answer_lineEdit_1")
        self.argument_lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_21.setGeometry(QtCore.QRect(210, 80, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_21.setFont(font)
        self.argument_lineEdit_21.setObjectName("argument_lineEdit_21")
        self.argument_lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_22.setGeometry(QtCore.QRect(360, 80, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_22.setFont(font)
        self.argument_lineEdit_22.setObjectName("argument_lineEdit_22")
        self.argument_lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_23.setGeometry(QtCore.QRect(510, 80, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_23.setFont(font)
        self.argument_lineEdit_23.setObjectName("argument_lineEdit_23")
        self.answer_lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_lineEdit_2.setGeometry(QtCore.QRect(670, 80, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_lineEdit_2.setFont(font)
        self.answer_lineEdit_2.setObjectName("answer_lineEdit_2")
        self.argument_lineEdit_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_31.setGeometry(QtCore.QRect(210, 130, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_31.setFont(font)
        self.argument_lineEdit_31.setObjectName("argument_lineEdit_31")
        self.argument_lineEdit_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_32.setGeometry(QtCore.QRect(360, 130, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_32.setFont(font)
        self.argument_lineEdit_32.setObjectName("argument_lineEdit_32")
        self.argument_lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_33.setGeometry(QtCore.QRect(510, 130, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_33.setFont(font)
        self.argument_lineEdit_33.setObjectName("argument_lineEdit_33")
        self.answer_lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_lineEdit_3.setGeometry(QtCore.QRect(670, 130, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_lineEdit_3.setFont(font)
        self.answer_lineEdit_3.setObjectName("answer_lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 30, 94, 27))
        self.pushButton.setObjectName("pushButton")
        self.brace_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.brace_label_2.setGeometry(QtCore.QRect(90, 590, 41, 161))
        self.brace_label_2.setText("")
        self.brace_label_2.setPixmap(QtGui.QPixmap("brace.png"))
        self.brace_label_2.setObjectName("brace_label_2")
        self.result_system_label_12 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_12.setGeometry(QtCore.QRect(270, 590, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_12.setFont(font)
        self.result_system_label_12.setText("")
        self.result_system_label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_12.setObjectName("result_system_label_12")
        self.result_system_answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_answer_label_1.setGeometry(QtCore.QRect(570, 590, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_answer_label_1.setFont(font)
        self.result_system_answer_label_1.setText("")
        self.result_system_answer_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.result_system_answer_label_1.setObjectName("result_system_answer_label_1")
        self.result_system_label_13 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_13.setGeometry(QtCore.QRect(420, 590, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_13.setFont(font)
        self.result_system_label_13.setText("")
        self.result_system_label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_13.setObjectName("result_system_label_13")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(540, 600, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(240, 700, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(390, 700, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.result_system_label_31 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_31.setEnabled(True)
        self.result_system_label_31.setGeometry(QtCore.QRect(140, 690, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_31.setFont(font)
        self.result_system_label_31.setText("")
        self.result_system_label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_31.setObjectName("result_system_label_31")
        self.x31_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x31_label_3.setGeometry(QtCore.QRect(510, 590, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x31_label_3.setFont(font)
        self.x31_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x31_label_3.setObjectName("x31_label_3")
        self.result_system_answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_answer_label_2.setGeometry(QtCore.QRect(570, 640, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_answer_label_2.setFont(font)
        self.result_system_answer_label_2.setText("")
        self.result_system_answer_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.result_system_answer_label_2.setObjectName("result_system_answer_label_2")
        self.result_system_answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_answer_label_3.setGeometry(QtCore.QRect(570, 690, 95, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_answer_label_3.setFont(font)
        self.result_system_answer_label_3.setText("")
        self.result_system_answer_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.result_system_answer_label_3.setObjectName("result_system_answer_label_3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(390, 650, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.x11_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x11_label_3.setGeometry(QtCore.QRect(210, 590, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x11_label_3.setFont(font)
        self.x11_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x11_label_3.setObjectName("x11_label_3")
        self.result_system_label_33 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_33.setGeometry(QtCore.QRect(420, 690, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_33.setFont(font)
        self.result_system_label_33.setText("")
        self.result_system_label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_33.setObjectName("result_system_label_33")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(540, 700, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.x21_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x21_label_3.setGeometry(QtCore.QRect(360, 590, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x21_label_3.setFont(font)
        self.x21_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x21_label_3.setObjectName("x21_label_3")
        self.x32_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x32_label_3.setGeometry(QtCore.QRect(510, 640, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x32_label_3.setFont(font)
        self.x32_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x32_label_3.setObjectName("x32_label_3")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(540, 650, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.result_system_label_32 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_32.setGeometry(QtCore.QRect(290, 690, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_32.setFont(font)
        self.result_system_label_32.setText("")
        self.result_system_label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_32.setObjectName("result_system_label_32")
        self.result_system_label_11 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_11.setEnabled(True)
        self.result_system_label_11.setGeometry(QtCore.QRect(120, 590, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_11.setFont(font)
        self.result_system_label_11.setText("")
        self.result_system_label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_11.setObjectName("result_system_label_11")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(240, 600, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.result_system_label_22 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_22.setGeometry(QtCore.QRect(270, 640, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_22.setFont(font)
        self.result_system_label_22.setText("")
        self.result_system_label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_22.setObjectName("result_system_label_22")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(390, 600, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(240, 650, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.x33_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x33_label_3.setGeometry(QtCore.QRect(510, 690, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x33_label_3.setFont(font)
        self.x33_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x33_label_3.setObjectName("x33_label_3")
        self.result_system_label_23 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_23.setGeometry(QtCore.QRect(420, 640, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_23.setFont(font)
        self.result_system_label_23.setText("")
        self.result_system_label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_23.setObjectName("result_system_label_23")
        self.result_system_label_21 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_21.setEnabled(True)
        self.result_system_label_21.setGeometry(QtCore.QRect(140, 640, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_21.setFont(font)
        self.result_system_label_21.setText("")
        self.result_system_label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_21.setObjectName("result_system_label_21")
        self.x22_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x22_label_3.setGeometry(QtCore.QRect(360, 640, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x22_label_3.setFont(font)
        self.x22_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x22_label_3.setObjectName("x22_label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.matrixA_label.setText(_translate("MainWindow", "A ="))
        self.matrixB_label.setText(_translate("MainWindow", "B ="))
        self.tilde_label_1.setText(_translate("MainWindow", "~"))
        self.tilde_label_2.setText(_translate("MainWindow", "~"))
        self.x11_label_2.setText(_translate("MainWindow", "x"))
        self.x22_label_2.setText(_translate("MainWindow", "y"))
        self.x13_label_2.setText(_translate("MainWindow", "x"))
        self.x31_label_2.setText(_translate("MainWindow", "z"))
        self.label_20.setText(_translate("MainWindow", "+"))
        self.x32_label_2.setText(_translate("MainWindow", "z"))
        self.label_23.setText(_translate("MainWindow", "="))
        self.label_14.setText(_translate("MainWindow", "+"))
        self.x12_label_2.setText(_translate("MainWindow", "x"))
        self.x21_label_2.setText(_translate("MainWindow", "y"))
        self.label_17.setText(_translate("MainWindow", "="))
        self.label_15.setText(_translate("MainWindow", "+"))
        self.label_18.setText(_translate("MainWindow", "+"))
        self.x33_label_2.setText(_translate("MainWindow", "z"))
        self.label_24.setText(_translate("MainWindow", "+"))
        self.label_25.setText(_translate("MainWindow", "="))
        self.x23_label_2.setText(_translate("MainWindow", "y"))
        self.label_26.setText(_translate("MainWindow", "+"))
        self.pushButton.setText(_translate("MainWindow", "Далее"))
        self.label_27.setText(_translate("MainWindow", "="))
        self.label_21.setText(_translate("MainWindow", "+"))
        self.label_28.setText(_translate("MainWindow", "+"))
        self.x31_label_3.setText(_translate("MainWindow", "z"))
        self.label_16.setText(_translate("MainWindow", "+"))
        self.x11_label_3.setText(_translate("MainWindow", "x"))
        self.label_29.setText(_translate("MainWindow", "="))
        self.x21_label_3.setText(_translate("MainWindow", "y"))
        self.x32_label_3.setText(_translate("MainWindow", "z"))
        self.label_19.setText(_translate("MainWindow", "="))
        self.label_22.setText(_translate("MainWindow", "+"))
        self.label_30.setText(_translate("MainWindow", "+"))
        self.label_31.setText(_translate("MainWindow", "+"))
        self.x33_label_3.setText(_translate("MainWindow", "z"))
        self.x22_label_3.setText(_translate("MainWindow", "y"))
