# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_gauss.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from dragLabel import DragLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1285, 719)
        MainWindow.setMinimumSize(QtCore.QSize(1285, 719))
        MainWindow.setMaximumSize(QtCore.QSize(1285, 719))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.brace_label = QtWidgets.QLabel(self.centralwidget)
        self.brace_label.setGeometry(QtCore.QRect(190, 30, 21, 111))
        self.brace_label.setText("")
        self.brace_label.setPixmap(QtGui.QPixmap("C:\\img\\brace.png"))
        self.brace_label.setObjectName("brace_label")
        self.matrixA_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrixA_bracket_label_1.setGeometry(QtCore.QRect(90, 160, 21, 111))
        self.matrixA_bracket_label_1.setText("")
        self.matrixA_bracket_label_1.setPixmap(QtGui.QPixmap("C:\\img\\skobka1.png"))
        self.matrixA_bracket_label_1.setObjectName("matrixA_bracket_label_1")
        self.matrixA_label_11 = DragLabel(self.centralwidget)
        self.matrixA_label_11.setGeometry(QtCore.QRect(110, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_11.setFont(font)
        self.matrixA_label_11.setText("")
        self.matrixA_label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_11.setObjectName("matrixA_label_11")
        self.matrixA_label_21 = DragLabel(self.centralwidget)
        self.matrixA_label_21.setGeometry(QtCore.QRect(110, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_21.setFont(font)
        self.matrixA_label_21.setText("")
        self.matrixA_label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_21.setObjectName("matrixA_label_21")
        self.matrixA_label_31 = DragLabel(self.centralwidget)
        self.matrixA_label_31.setGeometry(QtCore.QRect(110, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_31.setFont(font)
        self.matrixA_label_31.setText("")
        self.matrixA_label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_31.setObjectName("matrixA_label_31")
        self.matrixA_label_12 = DragLabel(self.centralwidget)
        self.matrixA_label_12.setGeometry(QtCore.QRect(190, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_12.setFont(font)
        self.matrixA_label_12.setText("")
        self.matrixA_label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_12.setObjectName("matrixA_label_12")
        self.matrixA_label_32 = DragLabel(self.centralwidget)
        self.matrixA_label_32.setGeometry(QtCore.QRect(190, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_32.setFont(font)
        self.matrixA_label_32.setText("")
        self.matrixA_label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_32.setObjectName("matrixA_label_32")
        self.matrixA_label_22 = DragLabel(self.centralwidget)
        self.matrixA_label_22.setGeometry(QtCore.QRect(190, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_22.setFont(font)
        self.matrixA_label_22.setText("")
        self.matrixA_label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_22.setObjectName("matrixA_label_22")
        self.matrixA_label_13 = DragLabel(self.centralwidget)
        self.matrixA_label_13.setGeometry(QtCore.QRect(270, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_13.setFont(font)
        self.matrixA_label_13.setText("")
        self.matrixA_label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_13.setObjectName("matrixA_label_13")
        self.matrixA_label_33 = DragLabel(self.centralwidget)
        self.matrixA_label_33.setGeometry(QtCore.QRect(270, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_33.setFont(font)
        self.matrixA_label_33.setText("")
        self.matrixA_label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_33.setObjectName("matrixA_label_33")
        self.matrixA_label_23 = DragLabel(self.centralwidget)
        self.matrixA_label_23.setGeometry(QtCore.QRect(270, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label_23.setFont(font)
        self.matrixA_label_23.setText("")
        self.matrixA_label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matrixA_label_23.setObjectName("matrixA_label_23")
        self.matrixA_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrixA_bracket_label_2.setGeometry(QtCore.QRect(360, 160, 21, 111))
        self.matrixA_bracket_label_2.setText("")
        self.matrixA_bracket_label_2.setPixmap(QtGui.QPixmap("C:\\img\\skobka2.png"))
        self.matrixA_bracket_label_2.setObjectName("matrixA_bracket_label_2")
        self.matrixB_1 = DragLabel(self.centralwidget)
        self.matrixB_1.setGeometry(QtCore.QRect(480, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixB_1.setFont(font)
        self.matrixB_1.setText("")
        self.matrixB_1.setAlignment(QtCore.Qt.AlignCenter)
        self.matrixB_1.setObjectName("matrixB_1")
        self.matrixB_3 = DragLabel(self.centralwidget)
        self.matrixB_3.setGeometry(QtCore.QRect(480, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixB_3.setFont(font)
        self.matrixB_3.setText("")
        self.matrixB_3.setAlignment(QtCore.Qt.AlignCenter)
        self.matrixB_3.setObjectName("matrixB_3")
        self.matrixB_2 = DragLabel(self.centralwidget)
        self.matrixB_2.setGeometry(QtCore.QRect(480, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixB_2.setFont(font)
        self.matrixB_2.setText("")
        self.matrixB_2.setAlignment(QtCore.Qt.AlignCenter)
        self.matrixB_2.setObjectName("matrixB_2")
        self.matrixB_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrixB_bracket_label_1.setGeometry(QtCore.QRect(460, 160, 21, 111))
        self.matrixB_bracket_label_1.setText("")
        self.matrixB_bracket_label_1.setPixmap(QtGui.QPixmap("C:\\img\\skobka1.png"))
        self.matrixB_bracket_label_1.setObjectName("matrixB_bracket_label_1")
        self.matrixB_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrixB_bracket_label_2.setGeometry(QtCore.QRect(560, 160, 21, 111))
        self.matrixB_bracket_label_2.setText("")
        self.matrixB_bracket_label_2.setPixmap(QtGui.QPixmap("C:\\img\\skobka2.png"))
        self.matrixB_bracket_label_2.setObjectName("matrixB_bracket_label_2")
        self.matrixA_label = QtWidgets.QLabel(self.centralwidget)
        self.matrixA_label.setGeometry(QtCore.QRect(30, 190, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixA_label.setFont(font)
        self.matrixA_label.setObjectName("matrixA_label")
        self.matrixB_label = QtWidgets.QLabel(self.centralwidget)
        self.matrixB_label.setGeometry(QtCore.QRect(400, 190, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrixB_label.setFont(font)
        self.matrixB_label.setObjectName("matrixB_label")
        self.matrix1_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrix1_bracket_label_1.setGeometry(QtCore.QRect(20, 300, 21, 111))
        self.matrix1_bracket_label_1.setText("")
        self.matrix1_bracket_label_1.setPixmap(QtGui.QPixmap("C:\\img\\skobka1.png"))
        self.matrix1_bracket_label_1.setObjectName("matrix1_bracket_label_1")
        self.matrix_1_31 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_31.setGeometry(QtCore.QRect(30, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_31.setFont(font)
        self.matrix_1_31.setText("")
        self.matrix_1_31.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_31.setObjectName("matrix_1_31")
        self.matrix_1_23 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_23.setGeometry(QtCore.QRect(190, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_23.setFont(font)
        self.matrix_1_23.setText("")
        self.matrix_1_23.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_23.setObjectName("matrix_1_23")
        self.matrix_1_11 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_11.setGeometry(QtCore.QRect(30, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_11.setFont(font)
        self.matrix_1_11.setText("")
        self.matrix_1_11.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_11.setObjectName("matrix_1_11")
        self.matrix_1_22 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_22.setGeometry(QtCore.QRect(110, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_22.setFont(font)
        self.matrix_1_22.setText("")
        self.matrix_1_22.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_22.setObjectName("matrix_1_22")
        self.matrix_1_32 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_32.setGeometry(QtCore.QRect(110, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_32.setFont(font)
        self.matrix_1_32.setText("")
        self.matrix_1_32.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_32.setObjectName("matrix_1_32")
        self.matrix_1_33 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_33.setGeometry(QtCore.QRect(190, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_33.setFont(font)
        self.matrix_1_33.setText("")
        self.matrix_1_33.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_33.setObjectName("matrix_1_33")
        self.matrix_1_12 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_12.setGeometry(QtCore.QRect(110, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_12.setFont(font)
        self.matrix_1_12.setText("")
        self.matrix_1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_12.setObjectName("matrix_1_12")
        self.matrix_1_13 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_13.setGeometry(QtCore.QRect(190, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_13.setFont(font)
        self.matrix_1_13.setText("")
        self.matrix_1_13.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_13.setObjectName("matrix_1_13")
        self.matrix_1_21 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_21.setGeometry(QtCore.QRect(30, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_21.setFont(font)
        self.matrix_1_21.setText("")
        self.matrix_1_21.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_21.setObjectName("matrix_1_21")
        self.matrix1_vertLine_label = QtWidgets.QLabel(self.centralwidget)
        self.matrix1_vertLine_label.setGeometry(QtCore.QRect(290, 310, 21, 101))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix1_vertLine_label.setFont(font)
        self.matrix1_vertLine_label.setText("")
        self.matrix1_vertLine_label.setPixmap(QtGui.QPixmap("C:\\img\\verticalLine2.jpg"))
        self.matrix1_vertLine_label.setObjectName("matrix1_vertLine_label")
        self.matrix_1_14 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_14.setGeometry(QtCore.QRect(300, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_14.setFont(font)
        self.matrix_1_14.setText("")
        self.matrix_1_14.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_14.setObjectName("matrix_1_14")
        self.matrix_1_24 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_24.setGeometry(QtCore.QRect(300, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_24.setFont(font)
        self.matrix_1_24.setText("")
        self.matrix_1_24.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_24.setObjectName("matrix_1_24")
        self.matrix_1_34 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_1_34.setGeometry(QtCore.QRect(300, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_1_34.setFont(font)
        self.matrix_1_34.setText("")
        self.matrix_1_34.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_1_34.setObjectName("matrix_1_34")
        self.matrix1_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrix1_bracket_label_2.setGeometry(QtCore.QRect(380, 300, 21, 111))
        self.matrix1_bracket_label_2.setText("")
        self.matrix1_bracket_label_2.setPixmap(QtGui.QPixmap("C:\\img\\skobka2.png"))
        self.matrix1_bracket_label_2.setObjectName("matrix1_bracket_label_2")
        self.tilde_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.tilde_label_1.setGeometry(QtCore.QRect(410, 340, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.tilde_label_1.setFont(font)
        self.tilde_label_1.setObjectName("tilde_label_1")
        self.matrix_2_11 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_11.setGeometry(QtCore.QRect(470, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_11.setFont(font)
        self.matrix_2_11.setText("")
        self.matrix_2_11.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_11.setObjectName("matrix_2_11")
        self.matrix_2_32 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_32.setGeometry(QtCore.QRect(550, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_32.setFont(font)
        self.matrix_2_32.setText("")
        self.matrix_2_32.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_32.setObjectName("matrix_2_32")
        self.matrix_2_34 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_34.setGeometry(QtCore.QRect(740, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_34.setFont(font)
        self.matrix_2_34.setText("")
        self.matrix_2_34.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_34.setObjectName("matrix_2_34")
        self.matrix_2_33 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_33.setGeometry(QtCore.QRect(630, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_33.setFont(font)
        self.matrix_2_33.setText("")
        self.matrix_2_33.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_33.setObjectName("matrix_2_33")
        self.matrix_2_21 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_21.setGeometry(QtCore.QRect(470, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_21.setFont(font)
        self.matrix_2_21.setText("")
        self.matrix_2_21.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_21.setObjectName("matrix_2_21")
        self.matrix_2_23 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_23.setGeometry(QtCore.QRect(630, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_23.setFont(font)
        self.matrix_2_23.setText("")
        self.matrix_2_23.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_23.setObjectName("matrix_2_23")
        self.matrix_2_12 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_12.setGeometry(QtCore.QRect(550, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_12.setFont(font)
        self.matrix_2_12.setText("")
        self.matrix_2_12.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_12.setObjectName("matrix_2_12")
        self.matrix_2_13 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_13.setGeometry(QtCore.QRect(630, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_13.setFont(font)
        self.matrix_2_13.setText("")
        self.matrix_2_13.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_13.setObjectName("matrix_2_13")
        self.matrix_2_31 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_31.setGeometry(QtCore.QRect(470, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_31.setFont(font)
        self.matrix_2_31.setText("")
        self.matrix_2_31.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_31.setObjectName("matrix_2_31")
        self.matrix2_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrix2_bracket_label_1.setGeometry(QtCore.QRect(460, 300, 21, 111))
        self.matrix2_bracket_label_1.setText("")
        self.matrix2_bracket_label_1.setPixmap(QtGui.QPixmap("C:\\img\\skobka1.png"))
        self.matrix2_bracket_label_1.setObjectName("matrix2_bracket_label_1")
        self.matrix_2_24 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_24.setGeometry(QtCore.QRect(740, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_24.setFont(font)
        self.matrix_2_24.setText("")
        self.matrix_2_24.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_24.setObjectName("matrix_2_24")
        self.matrix_2_14 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_14.setGeometry(QtCore.QRect(740, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_14.setFont(font)
        self.matrix_2_14.setText("")
        self.matrix_2_14.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_14.setObjectName("matrix_2_14")
        self.matrix2_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrix2_bracket_label_2.setGeometry(QtCore.QRect(820, 300, 21, 111))
        self.matrix2_bracket_label_2.setText("")
        self.matrix2_bracket_label_2.setPixmap(QtGui.QPixmap("C:\\img\\skobka2.png"))
        self.matrix2_bracket_label_2.setObjectName("matrix2_bracket_label_2")
        self.matrix_2_22 = QtWidgets.QLabel(self.centralwidget)
        self.matrix_2_22.setGeometry(QtCore.QRect(550, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_2_22.setFont(font)
        self.matrix_2_22.setText("")
        self.matrix_2_22.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_2_22.setObjectName("matrix_2_22")
        self.matrix_3_21 = DragLabel(self.centralwidget)
        self.matrix_3_21.setGeometry(QtCore.QRect(910, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_21.setFont(font)
        self.matrix_3_21.setText("")
        self.matrix_3_21.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_21.setObjectName("matrix_3_21")
        self.matrix_3_31 = DragLabel(self.centralwidget)
        self.matrix_3_31.setGeometry(QtCore.QRect(910, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_31.setFont(font)
        self.matrix_3_31.setText("")
        self.matrix_3_31.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_31.setObjectName("matrix_3_31")
        self.matrix3_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.matrix3_bracket_label_1.setGeometry(QtCore.QRect(900, 300, 21, 111))
        self.matrix3_bracket_label_1.setText("")
        self.matrix3_bracket_label_1.setPixmap(QtGui.QPixmap("C:\\img\\skobka1.png"))
        self.matrix3_bracket_label_1.setObjectName("matrix3_bracket_label_1")
        self.matrix_3_34 = DragLabel(self.centralwidget)
        self.matrix_3_34.setGeometry(QtCore.QRect(1180, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_34.setFont(font)
        self.matrix_3_34.setText("")
        self.matrix_3_34.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_34.setObjectName("matrix_3_34")
        self.matrix_3_33 = DragLabel(self.centralwidget)
        self.matrix_3_33.setGeometry(QtCore.QRect(1070, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_33.setFont(font)
        self.matrix_3_33.setText("")
        self.matrix_3_33.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_33.setObjectName("matrix_3_33")
        self.matrix_3_11 = DragLabel(self.centralwidget)
        self.matrix_3_11.setGeometry(QtCore.QRect(910, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_11.setFont(font)
        self.matrix_3_11.setText("")
        self.matrix_3_11.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_11.setObjectName("matrix_3_11")
        self.matrix_3_32 = DragLabel(self.centralwidget)
        self.matrix_3_32.setGeometry(QtCore.QRect(990, 370, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_32.setFont(font)
        self.matrix_3_32.setText("")
        self.matrix_3_32.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_32.setObjectName("matrix_3_32")
        self.matrix_3_23 = DragLabel(self.centralwidget)
        self.matrix_3_23.setGeometry(QtCore.QRect(1070, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_23.setFont(font)
        self.matrix_3_23.setText("")
        self.matrix_3_23.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_23.setObjectName("matrix_3_23")
        self.matrix3_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.matrix3_bracket_label_2.setGeometry(QtCore.QRect(1260, 300, 21, 111))
        self.matrix3_bracket_label_2.setText("")
        self.matrix3_bracket_label_2.setPixmap(QtGui.QPixmap("C:\\img\\skobka2.png"))
        self.matrix3_bracket_label_2.setObjectName("matrix3_bracket_label_2")
        self.matrix_3_13 = DragLabel(self.centralwidget)
        self.matrix_3_13.setGeometry(QtCore.QRect(1070, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_13.setFont(font)
        self.matrix_3_13.setText("")
        self.matrix_3_13.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_13.setObjectName("matrix_3_13")
        self.matrix_3_14 = DragLabel(self.centralwidget)
        self.matrix_3_14.setGeometry(QtCore.QRect(1180, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_14.setFont(font)
        self.matrix_3_14.setText("")
        self.matrix_3_14.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_14.setObjectName("matrix_3_14")
        self.matrix_3_22 = DragLabel(self.centralwidget)
        self.matrix_3_22.setGeometry(QtCore.QRect(990, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_22.setFont(font)
        self.matrix_3_22.setText("")
        self.matrix_3_22.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_22.setObjectName("matrix_3_22")
        self.matrix_3_12 = DragLabel(self.centralwidget)
        self.matrix_3_12.setGeometry(QtCore.QRect(990, 310, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_12.setFont(font)
        self.matrix_3_12.setText("")
        self.matrix_3_12.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_12.setObjectName("matrix_3_12")
        self.matrix_3_24 = DragLabel(self.centralwidget)
        self.matrix_3_24.setGeometry(QtCore.QRect(1180, 340, 85, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix_3_24.setFont(font)
        self.matrix_3_24.setText("")
        self.matrix_3_24.setAlignment(QtCore.Qt.AlignCenter)
        self.matrix_3_24.setObjectName("matrix_3_24")
        self.matrix2_vertLine_label = QtWidgets.QLabel(self.centralwidget)
        self.matrix2_vertLine_label.setGeometry(QtCore.QRect(730, 310, 21, 101))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.matrix2_vertLine_label.setFont(font)
        self.matrix2_vertLine_label.setText("")
        self.matrix2_vertLine_label.setPixmap(QtGui.QPixmap("C:\\img\\verticalLine2.jpg"))
        self.matrix2_vertLine_label.setObjectName("matrix2_vertLine_label")
        self.matrix3_vertLine_label = QtWidgets.QLabel(self.centralwidget)
        self.matrix3_vertLine_label.setGeometry(QtCore.QRect(1170, 310, 21, 101))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.matrix3_vertLine_label.setFont(font)
        self.matrix3_vertLine_label.setText("")
        self.matrix3_vertLine_label.setPixmap(QtGui.QPixmap("C:\\img\\verticalLine2.jpg"))
        self.matrix3_vertLine_label.setObjectName("matrix3_vertLine_label")
        self.augmentMatrix_label_33 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_33.setGeometry(QtCore.QRect(820, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_33.setFont(font)
        self.augmentMatrix_label_33.setText("")
        self.augmentMatrix_label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_33.setObjectName("augmentMatrix_label_33")
        self.augmentMatrix_bracket_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_bracket_label_1.setGeometry(QtCore.QRect(640, 160, 21, 111))
        self.augmentMatrix_bracket_label_1.setText("")
        self.augmentMatrix_bracket_label_1.setPixmap(QtGui.QPixmap("C:\\img\\skobka1.png"))
        self.augmentMatrix_bracket_label_1.setObjectName("augmentMatrix_bracket_label_1")
        self.augmentMatrix_label_11 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_11.setGeometry(QtCore.QRect(660, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_11.setFont(font)
        self.augmentMatrix_label_11.setText("")
        self.augmentMatrix_label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_11.setObjectName("augmentMatrix_label_11")
        self.augmentMatrix_label_21 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_21.setGeometry(QtCore.QRect(660, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_21.setFont(font)
        self.augmentMatrix_label_21.setText("")
        self.augmentMatrix_label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_21.setObjectName("augmentMatrix_label_21")
        self.augmentMatrix_label_22 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_22.setGeometry(QtCore.QRect(740, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_22.setFont(font)
        self.augmentMatrix_label_22.setText("")
        self.augmentMatrix_label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_22.setObjectName("augmentMatrix_label_22")
        self.augmentMatrix_label_24 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_24.setGeometry(QtCore.QRect(920, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_24.setFont(font)
        self.augmentMatrix_label_24.setText("")
        self.augmentMatrix_label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_24.setObjectName("augmentMatrix_label_24")
        self.augmentMatrix_bracket_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_bracket_label_2.setGeometry(QtCore.QRect(1000, 160, 21, 111))
        self.augmentMatrix_bracket_label_2.setText("")
        self.augmentMatrix_bracket_label_2.setPixmap(QtGui.QPixmap("C:\\img\\skobka2.png"))
        self.augmentMatrix_bracket_label_2.setObjectName("augmentMatrix_bracket_label_2")
        self.augmentMatrix_label_34 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_34.setGeometry(QtCore.QRect(920, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_34.setFont(font)
        self.augmentMatrix_label_34.setText("")
        self.augmentMatrix_label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_34.setObjectName("augmentMatrix_label_34")
        self.augmentMatrix_label_13 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_13.setGeometry(QtCore.QRect(820, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_13.setFont(font)
        self.augmentMatrix_label_13.setText("")
        self.augmentMatrix_label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_13.setObjectName("augmentMatrix_label_13")
        self.augmentMatrix_label_32 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_32.setGeometry(QtCore.QRect(740, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_32.setFont(font)
        self.augmentMatrix_label_32.setText("")
        self.augmentMatrix_label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_32.setObjectName("augmentMatrix_label_32")
        self.augmentMatrix_label_31 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_31.setGeometry(QtCore.QRect(660, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_31.setFont(font)
        self.augmentMatrix_label_31.setText("")
        self.augmentMatrix_label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_31.setObjectName("augmentMatrix_label_31")
        self.augmentMatrix_label_12 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_12.setGeometry(QtCore.QRect(740, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_12.setFont(font)
        self.augmentMatrix_label_12.setText("")
        self.augmentMatrix_label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_12.setObjectName("augmentMatrix_label_12")
        self.augmentMatrix_label_14 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_14.setGeometry(QtCore.QRect(920, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_14.setFont(font)
        self.augmentMatrix_label_14.setText("")
        self.augmentMatrix_label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_14.setObjectName("augmentMatrix_label_14")
        self.augmentMatrix_label_23 = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_label_23.setGeometry(QtCore.QRect(820, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_label_23.setFont(font)
        self.augmentMatrix_label_23.setText("")
        self.augmentMatrix_label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.augmentMatrix_label_23.setObjectName("augmentMatrix_label_23")
        self.augmentMatrix_vertLine_label = QtWidgets.QLabel(self.centralwidget)
        self.augmentMatrix_vertLine_label.setGeometry(QtCore.QRect(910, 170, 21, 101))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.augmentMatrix_vertLine_label.setFont(font)
        self.augmentMatrix_vertLine_label.setText("")
        self.augmentMatrix_vertLine_label.setPixmap(QtGui.QPixmap("C:\\img\\verticalLine2.jpg"))
        self.augmentMatrix_vertLine_label.setObjectName("augmentMatrix_vertLine_label")
        self.x11_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x11_label_2.setGeometry(QtCore.QRect(300, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x11_label_2.setFont(font)
        self.x11_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x11_label_2.setObjectName("x11_label_2")
        self.x22_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x22_label_2.setGeometry(QtCore.QRect(450, 60, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x22_label_2.setFont(font)
        self.x22_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x22_label_2.setObjectName("x22_label_2")
        self.x13_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x13_label_2.setGeometry(QtCore.QRect(300, 100, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x13_label_2.setFont(font)
        self.x13_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x13_label_2.setObjectName("x13_label_2")
        self.argument_label_13 = DragLabel(self.centralwidget)
        self.argument_label_13.setGeometry(QtCore.QRect(510, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_13.setFont(font)
        self.argument_label_13.setText("")
        self.argument_label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_13.setObjectName("argument_label_13")
        self.x31_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x31_label_2.setGeometry(QtCore.QRect(600, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x31_label_2.setFont(font)
        self.x31_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x31_label_2.setObjectName("x31_label_2")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(330, 100, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.answer_label_1 = DragLabel(self.centralwidget)
        self.answer_label_1.setGeometry(QtCore.QRect(660, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_1.setFont(font)
        self.answer_label_1.setText("")
        self.answer_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_label_1.setObjectName("answer_label_1")
        self.argument_label_21 = DragLabel(self.centralwidget)
        self.argument_label_21.setEnabled(True)
        self.argument_label_21.setGeometry(QtCore.QRect(210, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_21.setFont(font)
        self.argument_label_21.setText("")
        self.argument_label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_21.setObjectName("argument_label_21")
        self.x32_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x32_label_2.setGeometry(QtCore.QRect(600, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x32_label_2.setFont(font)
        self.x32_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x32_label_2.setObjectName("x32_label_2")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(630, 100, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(480, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.answer_label_3 = DragLabel(self.centralwidget)
        self.answer_label_3.setGeometry(QtCore.QRect(660, 100, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_3.setFont(font)
        self.answer_label_3.setText("")
        self.answer_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_label_3.setObjectName("answer_label_3")
        self.argument_label_33 = DragLabel(self.centralwidget)
        self.argument_label_33.setGeometry(QtCore.QRect(510, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_33.setFont(font)
        self.argument_label_33.setText("")
        self.argument_label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_33.setObjectName("argument_label_33")
        self.argument_label_32 = DragLabel(self.centralwidget)
        self.argument_label_32.setGeometry(QtCore.QRect(360, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_32.setFont(font)
        self.argument_label_32.setText("")
        self.argument_label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_32.setObjectName("argument_label_32")
        self.x12_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x12_label_2.setGeometry(QtCore.QRect(300, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x12_label_2.setFont(font)
        self.x12_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x12_label_2.setObjectName("x12_label_2")
        self.argument_label_11 = DragLabel(self.centralwidget)
        self.argument_label_11.setEnabled(True)
        self.argument_label_11.setGeometry(QtCore.QRect(210, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_11.setFont(font)
        self.argument_label_11.setText("")
        self.argument_label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_11.setObjectName("argument_label_11")
        self.argument_lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_11.setGeometry(QtCore.QRect(210, 40, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_11.setFont(font)
        self.argument_lineEdit_11.setObjectName("argument_lineEdit_11")
        self.x21_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x21_label_2.setGeometry(QtCore.QRect(450, 30, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x21_label_2.setFont(font)
        self.x21_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x21_label_2.setObjectName("x21_label_2")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(630, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(480, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.argument_label_22 = DragLabel(self.centralwidget)
        self.argument_label_22.setGeometry(QtCore.QRect(360, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_22.setFont(font)
        self.argument_label_22.setText("")
        self.argument_label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_22.setObjectName("argument_label_22")
        self.answer_label_2 = DragLabel(self.centralwidget)
        self.answer_label_2.setGeometry(QtCore.QRect(660, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_2.setFont(font)
        self.answer_label_2.setText("")
        self.answer_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_label_2.setObjectName("answer_label_2")
        self.argument_label_12 = DragLabel(self.centralwidget)
        self.argument_label_12.setGeometry(QtCore.QRect(360, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_12.setFont(font)
        self.argument_label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_12.setObjectName("argument_label_12")
        self.argument_label_31 = DragLabel(self.centralwidget)
        self.argument_label_31.setEnabled(True)
        self.argument_label_31.setGeometry(QtCore.QRect(210, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_31.setFont(font)
        self.argument_label_31.setText("")
        self.argument_label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_31.setObjectName("argument_label_31")
        self.argument_label_23 = DragLabel(self.centralwidget)
        self.argument_label_23.setGeometry(QtCore.QRect(510, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_23.setFont(font)
        self.argument_label_23.setText("")
        self.argument_label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.argument_label_23.setObjectName("argument_label_23")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(330, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.x33_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x33_label_2.setGeometry(QtCore.QRect(600, 100, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x33_label_2.setFont(font)
        self.x33_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x33_label_2.setObjectName("x33_label_2")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(330, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(630, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.x23_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.x23_label_2.setGeometry(QtCore.QRect(450, 90, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x23_label_2.setFont(font)
        self.x23_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x23_label_2.setObjectName("x23_label_2")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(480, 100, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.argument_lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_12.setGeometry(QtCore.QRect(360, 40, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_12.setFont(font)
        self.argument_lineEdit_12.setObjectName("argument_lineEdit_12")
        self.argument_lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_13.setGeometry(QtCore.QRect(510, 40, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_13.setFont(font)
        self.argument_lineEdit_13.setObjectName("argument_lineEdit_13")
        self.answer_lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_lineEdit_1.setGeometry(QtCore.QRect(670, 40, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.answer_lineEdit_1.setFont(font)
        self.answer_lineEdit_1.setObjectName("answer_lineEdit_1")
        self.argument_lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_21.setGeometry(QtCore.QRect(210, 70, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_21.setFont(font)
        self.argument_lineEdit_21.setObjectName("argument_lineEdit_21")
        self.argument_lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_22.setGeometry(QtCore.QRect(360, 70, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_22.setFont(font)
        self.argument_lineEdit_22.setObjectName("argument_lineEdit_22")
        self.argument_lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_23.setGeometry(QtCore.QRect(510, 70, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_23.setFont(font)
        self.argument_lineEdit_23.setObjectName("argument_lineEdit_23")
        self.answer_lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_lineEdit_2.setGeometry(QtCore.QRect(670, 70, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.answer_lineEdit_2.setFont(font)
        self.answer_lineEdit_2.setObjectName("answer_lineEdit_2")
        self.argument_lineEdit_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_31.setGeometry(QtCore.QRect(210, 100, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_31.setFont(font)
        self.argument_lineEdit_31.setObjectName("argument_lineEdit_31")
        self.argument_lineEdit_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_32.setGeometry(QtCore.QRect(360, 100, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_32.setFont(font)
        self.argument_lineEdit_32.setObjectName("argument_lineEdit_32")
        self.argument_lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.argument_lineEdit_33.setGeometry(QtCore.QRect(510, 100, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.argument_lineEdit_33.setFont(font)
        self.argument_lineEdit_33.setObjectName("argument_lineEdit_33")
        self.answer_lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.answer_lineEdit_3.setGeometry(QtCore.QRect(670, 100, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.answer_lineEdit_3.setFont(font)
        self.answer_lineEdit_3.setObjectName("answer_lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 30, 94, 27))
        self.pushButton.setObjectName("pushButton")
        self.brace_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.brace_label_2.setGeometry(QtCore.QRect(40, 430, 21, 111))
        self.brace_label_2.setText("")
        self.brace_label_2.setPixmap(QtGui.QPixmap("C:\\img\\brace.png"))
        self.brace_label_2.setObjectName("brace_label_2")
        self.result_system_label_12 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_12.setGeometry(QtCore.QRect(200, 430, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_12.setFont(font)
        self.result_system_label_12.setText("")
        self.result_system_label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_12.setObjectName("result_system_label_12")
        self.result_system_answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_answer_label_1.setGeometry(QtCore.QRect(500, 430, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_answer_label_1.setFont(font)
        self.result_system_answer_label_1.setText("")
        self.result_system_answer_label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result_system_answer_label_1.setObjectName("result_system_answer_label_1")
        self.result_system_label_13 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_13.setGeometry(QtCore.QRect(350, 430, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_13.setFont(font)
        self.result_system_label_13.setText("")
        self.result_system_label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_13.setObjectName("result_system_label_13")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(470, 430, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(170, 490, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(320, 490, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.result_system_label_31 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_31.setEnabled(True)
        self.result_system_label_31.setGeometry(QtCore.QRect(70, 490, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_31.setFont(font)
        self.result_system_label_31.setText("")
        self.result_system_label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_31.setObjectName("result_system_label_31")
        self.x31_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x31_label_3.setGeometry(QtCore.QRect(440, 430, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x31_label_3.setFont(font)
        self.x31_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x31_label_3.setObjectName("x31_label_3")
        self.result_system_answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_answer_label_2.setGeometry(QtCore.QRect(500, 460, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_answer_label_2.setFont(font)
        self.result_system_answer_label_2.setText("")
        self.result_system_answer_label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result_system_answer_label_2.setObjectName("result_system_answer_label_2")
        self.result_system_answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_answer_label_3.setGeometry(QtCore.QRect(500, 490, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_answer_label_3.setFont(font)
        self.result_system_answer_label_3.setText("")
        self.result_system_answer_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result_system_answer_label_3.setObjectName("result_system_answer_label_3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(320, 460, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.x11_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x11_label_3.setGeometry(QtCore.QRect(140, 430, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x11_label_3.setFont(font)
        self.x11_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x11_label_3.setObjectName("x11_label_3")
        self.result_system_label_33 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_33.setGeometry(QtCore.QRect(350, 490, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_33.setFont(font)
        self.result_system_label_33.setText("")
        self.result_system_label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_33.setObjectName("result_system_label_33")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(470, 490, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.x21_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x21_label_3.setGeometry(QtCore.QRect(290, 420, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x21_label_3.setFont(font)
        self.x21_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x21_label_3.setObjectName("x21_label_3")
        self.x32_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x32_label_3.setGeometry(QtCore.QRect(440, 460, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x32_label_3.setFont(font)
        self.x32_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x32_label_3.setObjectName("x32_label_3")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(470, 460, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.result_system_label_32 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_32.setGeometry(QtCore.QRect(220, 490, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_32.setFont(font)
        self.result_system_label_32.setText("")
        self.result_system_label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_32.setObjectName("result_system_label_32")
        self.result_system_label_11 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_11.setEnabled(True)
        self.result_system_label_11.setGeometry(QtCore.QRect(50, 430, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_11.setFont(font)
        self.result_system_label_11.setText("")
        self.result_system_label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_11.setObjectName("result_system_label_11")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(170, 430, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.result_system_label_22 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_22.setGeometry(QtCore.QRect(200, 460, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_22.setFont(font)
        self.result_system_label_22.setText("")
        self.result_system_label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_22.setObjectName("result_system_label_22")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(320, 430, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(170, 460, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.x33_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x33_label_3.setGeometry(QtCore.QRect(440, 490, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x33_label_3.setFont(font)
        self.x33_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x33_label_3.setObjectName("x33_label_3")
        self.result_system_label_23 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_23.setGeometry(QtCore.QRect(350, 460, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_23.setFont(font)
        self.result_system_label_23.setText("")
        self.result_system_label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_23.setObjectName("result_system_label_23")
        self.result_system_label_21 = QtWidgets.QLabel(self.centralwidget)
        self.result_system_label_21.setEnabled(True)
        self.result_system_label_21.setGeometry(QtCore.QRect(70, 460, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.result_system_label_21.setFont(font)
        self.result_system_label_21.setText("")
        self.result_system_label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_system_label_21.setObjectName("result_system_label_21")
        self.x22_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.x22_label_3.setGeometry(QtCore.QRect(290, 450, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x22_label_3.setFont(font)
        self.x22_label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.x22_label_3.setObjectName("x22_label_3")
        self.z_label = QtWidgets.QLabel(self.centralwidget)
        self.z_label.setGeometry(QtCore.QRect(80, 580, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.z_label.setFont(font)
        self.z_label.setObjectName("z_label")
        self.z_value_label = QtWidgets.QLabel(self.centralwidget)
        self.z_value_label.setGeometry(QtCore.QRect(140, 580, 1021, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.z_value_label.setFont(font)
        self.z_value_label.setText("")
        self.z_value_label.setObjectName("z_value_label")
        self.y_label = QtWidgets.QLabel(self.centralwidget)
        self.y_label.setGeometry(QtCore.QRect(80, 610, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.y_label.setFont(font)
        self.y_label.setObjectName("y_label")
        self.y_value_label = QtWidgets.QLabel(self.centralwidget)
        self.y_value_label.setGeometry(QtCore.QRect(140, 610, 1121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.y_value_label.setFont(font)
        self.y_value_label.setText("")
        self.y_value_label.setObjectName("y_value_label")
        self.x_label = QtWidgets.QLabel(self.centralwidget)
        self.x_label.setGeometry(QtCore.QRect(80, 660, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x_label.setFont(font)
        self.x_label.setObjectName("x_label")
        self.x_value_label = QtWidgets.QLabel(self.centralwidget)
        self.x_value_label.setGeometry(QtCore.QRect(140, 660, 1121, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.x_value_label.setFont(font)
        self.x_value_label.setText("")
        self.x_value_label.setObjectName("x_value_label")
        self.tilde_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.tilde_label_2.setGeometry(QtCore.QRect(850, 340, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.tilde_label_2.setFont(font)
        self.tilde_label_2.setObjectName("tilde_label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.matrixA_label.setText(_translate("MainWindow", "A = "))
        self.matrixB_label.setText(_translate("MainWindow", "B = "))
        self.tilde_label_1.setText(_translate("MainWindow", "~"))
        self.x11_label_2.setText(_translate("MainWindow", "x"))
        self.x22_label_2.setText(_translate("MainWindow", "y"))
        self.x13_label_2.setText(_translate("MainWindow", "x"))
        self.x31_label_2.setText(_translate("MainWindow", "z"))
        self.label_20.setText(_translate("MainWindow", "+"))
        self.x32_label_2.setText(_translate("MainWindow", "z"))
        self.label_23.setText(_translate("MainWindow", "="))
        self.label_14.setText(_translate("MainWindow", "+"))
        self.x12_label_2.setText(_translate("MainWindow", "x"))
        self.x21_label_2.setText(_translate("MainWindow", "y"))
        self.label_17.setText(_translate("MainWindow", "="))
        self.label_15.setText(_translate("MainWindow", "+"))
        self.argument_label_12.setText(_translate("MainWindow", "1"))
        self.label_18.setText(_translate("MainWindow", "+"))
        self.x33_label_2.setText(_translate("MainWindow", "z"))
        self.label_24.setText(_translate("MainWindow", "+"))
        self.label_25.setText(_translate("MainWindow", "="))
        self.x23_label_2.setText(_translate("MainWindow", "y"))
        self.label_26.setText(_translate("MainWindow", "+"))
        self.pushButton.setText(_translate("MainWindow", "Далее"))
        self.label_27.setText(_translate("MainWindow", "="))
        self.label_21.setText(_translate("MainWindow", "+"))
        self.label_28.setText(_translate("MainWindow", "+"))
        self.x31_label_3.setText(_translate("MainWindow", "z"))
        self.label_16.setText(_translate("MainWindow", "+"))
        self.x11_label_3.setText(_translate("MainWindow", "x"))
        self.label_29.setText(_translate("MainWindow", "="))
        self.x21_label_3.setText(_translate("MainWindow", "y"))
        self.x32_label_3.setText(_translate("MainWindow", "z"))
        self.label_19.setText(_translate("MainWindow", "="))
        self.label_22.setText(_translate("MainWindow", "+"))
        self.label_30.setText(_translate("MainWindow", "+"))
        self.label_31.setText(_translate("MainWindow", "+"))
        self.x33_label_3.setText(_translate("MainWindow", "z"))
        self.x22_label_3.setText(_translate("MainWindow", "y"))
        self.z_label.setText(_translate("MainWindow", "z = "))
        self.y_label.setText(_translate("MainWindow", "y = "))
        self.x_label.setText(_translate("MainWindow", "x = "))
        self.tilde_label_2.setText(_translate("MainWindow", "~"))
