# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1313, 922)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.argument_label_23 = QtWidgets.QLabel(self.centralwidget)
        self.argument_label_23.setGeometry(QtCore.QRect(320, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_23.setFont(font)
        self.argument_label_23.setObjectName("argument_label_23")
        self.argument_label_12 = QtWidgets.QLabel(self.centralwidget)
        self.argument_label_12.setGeometry(QtCore.QRect(210, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_12.setFont(font)
        self.argument_label_12.setObjectName("argument_label_12")
        self.argument_label_33 = QtWidgets.QLabel(self.centralwidget)
        self.argument_label_33.setGeometry(QtCore.QRect(360, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_33.setFont(font)
        self.argument_label_33.setObjectName("argument_label_33")
        self.answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.answer_label_2.setGeometry(QtCore.QRect(430, 70, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_2.setFont(font)
        self.answer_label_2.setObjectName("answer_label_2")
        self.answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.answer_label_3.setGeometry(QtCore.QRect(490, 120, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_3.setFont(font)
        self.answer_label_3.setObjectName("answer_label_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.argument_label_32 = QtWidgets.QLabel(self.centralwidget)
        self.argument_label_32.setGeometry(QtCore.QRect(230, 120, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_32.setFont(font)
        self.argument_label_32.setObjectName("argument_label_32")
        self.answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.answer_label_1.setGeometry(QtCore.QRect(430, 20, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_1.setFont(font)
        self.answer_label_1.setObjectName("answer_label_1")
        self.argument_label_13 = QtWidgets.QLabel(self.centralwidget)
        self.argument_label_13.setGeometry(QtCore.QRect(320, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_13.setFont(font)
        self.argument_label_13.setObjectName("argument_label_13")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(350, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.argument_label_11 = QtWidgets.QLabel(self.centralwidget)
        self.argument_label_11.setGeometry(QtCore.QRect(100, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_11.setFont(font)
        self.argument_label_11.setObjectName("argument_label_11")
        self.argument_label_31 = QtWidgets.QLabel(self.centralwidget)
        self.argument_label_31.setGeometry(QtCore.QRect(100, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_31.setFont(font)
        self.argument_label_31.setObjectName("argument_label_31")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(150, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.argument_label_22 = QtWidgets.QLabel(self.centralwidget)
        self.argument_label_22.setGeometry(QtCore.QRect(210, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_22.setFont(font)
        self.argument_label_22.setObjectName("argument_label_22")
        self.argument_label_21 = QtWidgets.QLabel(self.centralwidget)
        self.argument_label_21.setGeometry(QtCore.QRect(100, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_21.setFont(font)
        self.argument_label_21.setObjectName("argument_label_21")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(350, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 810, 94, 27))
        self.pushButton.setObjectName("pushButton")
        self.main_det_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.main_det_triangle_label.setGeometry(QtCore.QRect(20, 300, 51, 41))
        self.main_det_triangle_label.setText("")
        self.main_det_triangle_label.setPixmap(QtGui.QPixmap(":/newPrefix/triangle_2.png"))
        self.main_det_triangle_label.setObjectName("main_det_triangle_label")
        self.main_det_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_brice_label_1.setGeometry(QtCore.QRect(110, 230, 20, 171))
        self.main_det_brice_label_1.setText("")
        self.main_det_brice_label_1.setPixmap(QtGui.QPixmap(":/newPrefix/verticalLine2.jpg"))
        self.main_det_brice_label_1.setObjectName("main_det_brice_label_1")
        self.main_det_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_brice_label_2.setGeometry(QtCore.QRect(410, 230, 20, 171))
        self.main_det_brice_label_2.setText("")
        self.main_det_brice_label_2.setPixmap(QtGui.QPixmap(":/newPrefix/verticalLine2.jpg"))
        self.main_det_brice_label_2.setObjectName("main_det_brice_label_2")
        self.main_det_equals_2 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_equals_2.setGeometry(QtCore.QRect(420, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_equals_2.setFont(font)
        self.main_det_equals_2.setObjectName("main_det_equals_2")
        self.main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.main_det_label.setGeometry(QtCore.QRect(460, 280, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_label.setFont(font)
        self.main_det_label.setText("")
        self.main_det_label.setObjectName("main_det_label")
        self.det1_argument_22_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_22_label.setGeometry(QtCore.QRect(220, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_22_label.setFont(font)
        self.det1_argument_22_label.setObjectName("det1_argument_22_label")
        self.det1_argument_12_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_12_label.setGeometry(QtCore.QRect(220, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_12_label.setFont(font)
        self.det1_argument_12_label.setObjectName("det1_argument_12_label")
        self.det1_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_triangle_label.setGeometry(QtCore.QRect(10, 480, 51, 41))
        self.det1_triangle_label.setText("")
        self.det1_triangle_label.setPixmap(QtGui.QPixmap(":/newPrefix/triangle_2.png"))
        self.det1_triangle_label.setObjectName("det1_triangle_label")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(120, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.det_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det_1_label.setGeometry(QtCore.QRect(460, 470, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_1_label.setFont(font)
        self.det_1_label.setText("")
        self.det_1_label.setObjectName("det_1_label")
        self.det1_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det1_brice_label_2.setGeometry(QtCore.QRect(410, 430, 20, 171))
        self.det1_brice_label_2.setText("")
        self.det1_brice_label_2.setPixmap(QtGui.QPixmap(":/newPrefix/verticalLine2.jpg"))
        self.det1_brice_label_2.setObjectName("det1_brice_label_2")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(120, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.det1_argument_13_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_13_label.setGeometry(QtCore.QRect(320, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_13_label.setFont(font)
        self.det1_argument_13_label.setObjectName("det1_argument_13_label")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(120, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.det1_argument_33_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_33_label.setGeometry(QtCore.QRect(320, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_33_label.setFont(font)
        self.det1_argument_33_label.setObjectName("det1_argument_33_label")
        self.det1_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det1_brice_label_1.setGeometry(QtCore.QRect(110, 430, 20, 171))
        self.det1_brice_label_1.setText("")
        self.det1_brice_label_1.setPixmap(QtGui.QPixmap(":/newPrefix/verticalLine2.jpg"))
        self.det1_brice_label_1.setObjectName("det1_brice_label_1")
        self.det1_argument_23_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_23_label.setGeometry(QtCore.QRect(320, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_23_label.setFont(font)
        self.det1_argument_23_label.setObjectName("det1_argument_23_label")
        self.det1_argument_32_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_32_label.setGeometry(QtCore.QRect(220, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_32_label.setFont(font)
        self.det1_argument_32_label.setObjectName("det1_argument_32_label")
        self.det1_index_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_index_label.setGeometry(QtCore.QRect(60, 500, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.det1_index_label.setFont(font)
        self.det1_index_label.setObjectName("det1_index_label")
        self.det2_argument_33_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_33_label.setGeometry(QtCore.QRect(920, 340, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_33_label.setFont(font)
        self.det2_argument_33_label.setObjectName("det2_argument_33_label")
        self.det2_argument_13_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_13_label.setGeometry(QtCore.QRect(920, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_13_label.setFont(font)
        self.det2_argument_13_label.setObjectName("det2_argument_13_label")
        self.det2_argument_11_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_11_label.setGeometry(QtCore.QRect(720, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_11_label.setFont(font)
        self.det2_argument_11_label.setObjectName("det2_argument_11_label")
        self.det_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det_2_label.setGeometry(QtCore.QRect(1060, 270, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_2_label.setFont(font)
        self.det_2_label.setText("")
        self.det_2_label.setObjectName("det_2_label")
        self.det2_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det2_brice_label_1.setGeometry(QtCore.QRect(710, 230, 20, 171))
        self.det2_brice_label_1.setText("")
        self.det2_brice_label_1.setPixmap(QtGui.QPixmap(":/newPrefix/verticalLine2.jpg"))
        self.det2_brice_label_1.setObjectName("det2_brice_label_1")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(820, 340, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(820, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.det2_argument_21_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_21_label.setGeometry(QtCore.QRect(720, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_21_label.setFont(font)
        self.det2_argument_21_label.setObjectName("det2_argument_21_label")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(820, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.det2_index_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_index_label.setGeometry(QtCore.QRect(660, 310, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.det2_index_label.setFont(font)
        self.det2_index_label.setObjectName("det2_index_label")
        self.det2_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det2_brice_label_2.setGeometry(QtCore.QRect(1010, 230, 20, 171))
        self.det2_brice_label_2.setText("")
        self.det2_brice_label_2.setPixmap(QtGui.QPixmap(":/newPrefix/verticalLine2.jpg"))
        self.det2_brice_label_2.setObjectName("det2_brice_label_2")
        self.det2_argument_23_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_23_label.setGeometry(QtCore.QRect(920, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_23_label.setFont(font)
        self.det2_argument_23_label.setObjectName("det2_argument_23_label")
        self.det2_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_triangle_label.setGeometry(QtCore.QRect(610, 290, 51, 41))
        self.det2_triangle_label.setText("")
        self.det2_triangle_label.setPixmap(QtGui.QPixmap(":/newPrefix/triangle_2.png"))
        self.det2_triangle_label.setObjectName("det2_triangle_label")
        self.det2_argument_31_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_31_label.setGeometry(QtCore.QRect(720, 340, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_31_label.setFont(font)
        self.det2_argument_31_label.setObjectName("det2_argument_31_label")
        self.det_3_label = QtWidgets.QLabel(self.centralwidget)
        self.det_3_label.setGeometry(QtCore.QRect(1060, 470, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_3_label.setFont(font)
        self.det_3_label.setText("")
        self.det_3_label.setObjectName("det_3_label")
        self.det3_argument_22_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_22_label.setGeometry(QtCore.QRect(820, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_22_label.setFont(font)
        self.det3_argument_22_label.setObjectName("det3_argument_22_label")
        self.det3_argument_31_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_31_label.setGeometry(QtCore.QRect(720, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_31_label.setFont(font)
        self.det3_argument_31_label.setObjectName("det3_argument_31_label")
        self.det3_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det3_brice_label_2.setGeometry(QtCore.QRect(1010, 430, 20, 171))
        self.det3_brice_label_2.setText("")
        self.det3_brice_label_2.setPixmap(QtGui.QPixmap(":/newPrefix/verticalLine2.jpg"))
        self.det3_brice_label_2.setObjectName("det3_brice_label_2")
        self.det3_argument_32_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_32_label.setGeometry(QtCore.QRect(820, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_32_label.setFont(font)
        self.det3_argument_32_label.setObjectName("det3_argument_32_label")
        self.det3_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det3_brice_label_1.setGeometry(QtCore.QRect(710, 430, 20, 171))
        self.det3_brice_label_1.setText("")
        self.det3_brice_label_1.setPixmap(QtGui.QPixmap(":/newPrefix/verticalLine2.jpg"))
        self.det3_brice_label_1.setObjectName("det3_brice_label_1")
        self.det3_argument_21_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_21_label.setGeometry(QtCore.QRect(720, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_21_label.setFont(font)
        self.det3_argument_21_label.setObjectName("det3_argument_21_label")
        self.det3_index_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_index_label.setGeometry(QtCore.QRect(660, 520, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.det3_index_label.setFont(font)
        self.det3_index_label.setObjectName("det3_index_label")
        self.det3_argument_11_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_11_label.setGeometry(QtCore.QRect(720, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_11_label.setFont(font)
        self.det3_argument_11_label.setObjectName("det3_argument_11_label")
        self.det3_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_triangle_label.setGeometry(QtCore.QRect(610, 490, 51, 41))
        self.det3_triangle_label.setText("")
        self.det3_triangle_label.setPixmap(QtGui.QPixmap(":/newPrefix/triangle_2.png"))
        self.det3_triangle_label.setObjectName("det3_triangle_label")
        self.label_75 = QtWidgets.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(920, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.det3_argument_12_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_12_label.setGeometry(QtCore.QRect(820, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_12_label.setFont(font)
        self.det3_argument_12_label.setObjectName("det3_argument_12_label")
        self.label_77 = QtWidgets.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(920, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(920, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(290, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(200, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(280, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(330, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(410, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(460, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(400, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.det2_equals_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_equals_2_label.setGeometry(QtCore.QRect(1020, 290, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_equals_2_label.setFont(font)
        self.det2_equals_2_label.setObjectName("det2_equals_2_label")
        self.main_det_equals_1 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_equals_1.setGeometry(QtCore.QRect(70, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_equals_1.setFont(font)
        self.main_det_equals_1.setObjectName("main_det_equals_1")
        self.det2_equals_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_equals_1_label.setGeometry(QtCore.QRect(670, 290, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_equals_1_label.setFont(font)
        self.det2_equals_1_label.setObjectName("det2_equals_1_label")
        self.det1_equals_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_equals_1_label.setGeometry(QtCore.QRect(70, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_equals_1_label.setFont(font)
        self.det1_equals_1_label.setObjectName("det1_equals_1_label")
        self.det3_equals_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_equals_1_label.setGeometry(QtCore.QRect(670, 500, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_equals_1_label.setFont(font)
        self.det3_equals_1_label.setObjectName("det3_equals_1_label")
        self.det1_equals_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_equals_2_label.setGeometry(QtCore.QRect(420, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_equals_2_label.setFont(font)
        self.det1_equals_2_label.setObjectName("det1_equals_2_label")
        self.det3_equals_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_equals_2_label.setGeometry(QtCore.QRect(1020, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_equals_2_label.setFont(font)
        self.det3_equals_2_label.setObjectName("det3_equals_2_label")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(150, 810, 94, 27))
        self.pushButton_close.setObjectName("pushButton_close")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "="))
        self.argument_label_23.setText(_translate("MainWindow", "6"))
        self.argument_label_12.setText(_translate("MainWindow", "1"))
        self.argument_label_33.setText(_translate("MainWindow", "18"))
        self.answer_label_2.setText(_translate("MainWindow", "132"))
        self.answer_label_3.setText(_translate("MainWindow", "536"))
        self.label_3.setText(_translate("MainWindow", "+"))
        self.argument_label_32.setText(_translate("MainWindow", "23"))
        self.answer_label_1.setText(_translate("MainWindow", "77"))
        self.argument_label_13.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "x2"))
        self.label_2.setText(_translate("MainWindow", "x1"))
        self.label_17.setText(_translate("MainWindow", "x3"))
        self.argument_label_11.setText(_translate("MainWindow", "5"))
        self.argument_label_31.setText(_translate("MainWindow", "12"))
        self.label_18.setText(_translate("MainWindow", "x1"))
        self.argument_label_22.setText(_translate("MainWindow", "3"))
        self.argument_label_21.setText(_translate("MainWindow", "4"))
        self.label_4.setText(_translate("MainWindow", "x1"))
        self.label.setText(_translate("MainWindow", "x2"))
        self.label_24.setText(_translate("MainWindow", "x3"))
        self.pushButton.setText(_translate("MainWindow", "next"))
        self.main_det_equals_2.setText(_translate("MainWindow", "="))
        self.det1_argument_22_label.setText(_translate("MainWindow", "100"))
        self.det1_argument_12_label.setText(_translate("MainWindow", "100"))
        self.label_39.setText(_translate("MainWindow", "100"))
        self.label_41.setText(_translate("MainWindow", "100"))
        self.det1_argument_13_label.setText(_translate("MainWindow", "100"))
        self.label_43.setText(_translate("MainWindow", "100"))
        self.det1_argument_33_label.setText(_translate("MainWindow", "100"))
        self.det1_argument_23_label.setText(_translate("MainWindow", "100"))
        self.det1_argument_32_label.setText(_translate("MainWindow", "100"))
        self.det1_index_label.setText(_translate("MainWindow", "1"))
        self.det2_argument_33_label.setText(_translate("MainWindow", "100"))
        self.det2_argument_13_label.setText(_translate("MainWindow", "100"))
        self.det2_argument_11_label.setText(_translate("MainWindow", "100"))
        self.label_54.setText(_translate("MainWindow", "100"))
        self.label_55.setText(_translate("MainWindow", "100"))
        self.det2_argument_21_label.setText(_translate("MainWindow", "100"))
        self.label_57.setText(_translate("MainWindow", "100"))
        self.det2_index_label.setText(_translate("MainWindow", "2"))
        self.det2_argument_23_label.setText(_translate("MainWindow", "100"))
        self.det2_argument_31_label.setText(_translate("MainWindow", "100"))
        self.det3_argument_22_label.setText(_translate("MainWindow", "100"))
        self.det3_argument_31_label.setText(_translate("MainWindow", "100"))
        self.det3_argument_32_label.setText(_translate("MainWindow", "100"))
        self.det3_argument_21_label.setText(_translate("MainWindow", "100"))
        self.det3_index_label.setText(_translate("MainWindow", "3"))
        self.det3_argument_11_label.setText(_translate("MainWindow", "100"))
        self.label_75.setText(_translate("MainWindow", "100"))
        self.det3_argument_12_label.setText(_translate("MainWindow", "100"))
        self.label_77.setText(_translate("MainWindow", "100"))
        self.label_78.setText(_translate("MainWindow", "100"))
        self.label_8.setText(_translate("MainWindow", "+"))
        self.label_6.setText(_translate("MainWindow", "+"))
        self.label_10.setText(_translate("MainWindow", "+"))
        self.label_19.setText(_translate("MainWindow", "+"))
        self.label_20.setText(_translate("MainWindow", "x2"))
        self.label_21.setText(_translate("MainWindow", "+"))
        self.label_23.setText(_translate("MainWindow", "x3"))
        self.label_22.setText(_translate("MainWindow", "="))
        self.label_16.setText(_translate("MainWindow", "="))
        self.det2_equals_2_label.setText(_translate("MainWindow", "="))
        self.main_det_equals_1.setText(_translate("MainWindow", "="))
        self.det2_equals_1_label.setText(_translate("MainWindow", "="))
        self.det1_equals_1_label.setText(_translate("MainWindow", "="))
        self.det3_equals_1_label.setText(_translate("MainWindow", "="))
        self.det1_equals_2_label.setText(_translate("MainWindow", "="))
        self.det3_equals_2_label.setText(_translate("MainWindow", "="))
        self.pushButton_close.setText(_translate("MainWindow", "close"))

import x_rc
