# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from dragLabel import DragLabel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1757, 922)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(400, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.argument_label_23 = DragLabel(self.centralwidget)
        self.argument_label_23.setGeometry(QtCore.QRect(320, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_23.setFont(font)
        self.argument_label_23.setObjectName("argument_label_23")
        self.argument_label_12 = DragLabel(self.centralwidget)
        self.argument_label_12.setGeometry(QtCore.QRect(210, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_12.setFont(font)
        self.argument_label_12.setObjectName("argument_label_12")
        self.argument_label_33 = DragLabel(self.centralwidget)
        self.argument_label_33.setGeometry(QtCore.QRect(360, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_33.setFont(font)
        self.argument_label_33.setObjectName("argument_label_33")
        self.answer_label_2 = DragLabel(self.centralwidget)
        self.answer_label_2.setGeometry(QtCore.QRect(430, 70, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_2.setFont(font)
        self.answer_label_2.setObjectName("answer_label_2")
        self.answer_label_3 = DragLabel(self.centralwidget)
        self.answer_label_3.setGeometry(QtCore.QRect(490, 120, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_3.setFont(font)
        self.answer_label_3.setObjectName("answer_label_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.argument_label_32 = DragLabel(self.centralwidget)
        self.argument_label_32.setGeometry(QtCore.QRect(230, 120, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_32.setFont(font)
        self.argument_label_32.setObjectName("argument_label_32")
        self.answer_label_1 = DragLabel(self.centralwidget)
        self.answer_label_1.setGeometry(QtCore.QRect(430, 20, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.answer_label_1.setFont(font)
        self.answer_label_1.setObjectName("answer_label_1")
        self.argument_label_13 = DragLabel(self.centralwidget)
        self.argument_label_13.setGeometry(QtCore.QRect(320, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_13.setFont(font)
        self.argument_label_13.setObjectName("argument_label_13")
        self.x22_label = QtWidgets.QLabel(self.centralwidget)
        self.x22_label.setGeometry(QtCore.QRect(240, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x22_label.setFont(font)
        self.x22_label.setObjectName("x22_label")
        self.x12_label = QtWidgets.QLabel(self.centralwidget)
        self.x12_label.setGeometry(QtCore.QRect(130, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x12_label.setFont(font)
        self.x12_label.setObjectName("x12_label")
        self.x32_label = QtWidgets.QLabel(self.centralwidget)
        self.x32_label.setGeometry(QtCore.QRect(350, 70, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x32_label.setFont(font)
        self.x32_label.setObjectName("x32_label")
        self.argument_label_11 = DragLabel(self.centralwidget)
        self.argument_label_11.setEnabled(True)
        self.argument_label_11.setGeometry(QtCore.QRect(100, 20, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_11.setFont(font)
        self.argument_label_11.setObjectName("argument_label_11")
        self.argument_label_31 = DragLabel(self.centralwidget)
        self.argument_label_31.setEnabled(True)
        self.argument_label_31.setGeometry(QtCore.QRect(100, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_31.setFont(font)
        self.argument_label_31.setObjectName("argument_label_31")
        self.x13_label = QtWidgets.QLabel(self.centralwidget)
        self.x13_label.setGeometry(QtCore.QRect(150, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x13_label.setFont(font)
        self.x13_label.setObjectName("x13_label")
        self.argument_label_22 = DragLabel(self.centralwidget)
        self.argument_label_22.setGeometry(QtCore.QRect(210, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_22.setFont(font)
        self.argument_label_22.setObjectName("argument_label_22")
        self.argument_label_21 = DragLabel(self.centralwidget)
        self.argument_label_21.setEnabled(True)
        self.argument_label_21.setGeometry(QtCore.QRect(100, 70, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.argument_label_21.setFont(font)
        self.argument_label_21.setObjectName("argument_label_21")
        self.x11_label = QtWidgets.QLabel(self.centralwidget)
        self.x11_label.setGeometry(QtCore.QRect(130, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x11_label.setFont(font)
        self.x11_label.setObjectName("x11_label")
        self.x21_label = QtWidgets.QLabel(self.centralwidget)
        self.x21_label.setGeometry(QtCore.QRect(240, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x21_label.setFont(font)
        self.x21_label.setObjectName("x21_label")
        self.x31_label = QtWidgets.QLabel(self.centralwidget)
        self.x31_label.setGeometry(QtCore.QRect(350, 20, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x31_label.setFont(font)
        self.x31_label.setObjectName("x31_label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 810, 94, 27))
        self.pushButton.setObjectName("pushButton")
        self.main_det_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.main_det_triangle_label.setGeometry(QtCore.QRect(170, 300, 51, 41))
        self.main_det_triangle_label.setText("")
        self.main_det_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.main_det_triangle_label.setObjectName("main_det_triangle_label")
        self.main_det_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_brice_label_1.setGeometry(QtCore.QRect(260, 230, 20, 171))
        self.main_det_brice_label_1.setText("")
        self.main_det_brice_label_1.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.main_det_brice_label_1.setObjectName("main_det_brice_label_1")
        self.main_det_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_brice_label_2.setGeometry(QtCore.QRect(560, 230, 20, 171))
        self.main_det_brice_label_2.setText("")
        self.main_det_brice_label_2.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.main_det_brice_label_2.setObjectName("main_det_brice_label_2")
        self.main_det_equals_2 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_equals_2.setGeometry(QtCore.QRect(570, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_equals_2.setFont(font)
        self.main_det_equals_2.setObjectName("main_det_equals_2")
        self.main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.main_det_label.setGeometry(QtCore.QRect(610, 280, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_label.setFont(font)
        self.main_det_label.setText("")
        self.main_det_label.setObjectName("main_det_label")
        self.det1_argument_22_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_22_label.setGeometry(QtCore.QRect(370, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_22_label.setFont(font)
        self.det1_argument_22_label.setText("")
        self.det1_argument_22_label.setObjectName("det1_argument_22_label")
        self.det1_argument_12_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_12_label.setGeometry(QtCore.QRect(370, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_12_label.setFont(font)
        self.det1_argument_12_label.setText("")
        self.det1_argument_12_label.setObjectName("det1_argument_12_label")
        self.det1_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_triangle_label.setGeometry(QtCore.QRect(160, 480, 51, 41))
        self.det1_triangle_label.setText("")
        self.det1_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.det1_triangle_label.setObjectName("det1_triangle_label")
        self.det1_answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det1_answer_label_1.setGeometry(QtCore.QRect(270, 440, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_answer_label_1.setFont(font)
        self.det1_answer_label_1.setText("")
        self.det1_answer_label_1.setObjectName("det1_answer_label_1")
        self.det_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det_1_label.setGeometry(QtCore.QRect(610, 470, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_1_label.setFont(font)
        self.det_1_label.setText("")
        self.det_1_label.setObjectName("det_1_label")
        self.det1_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det1_brice_label_2.setGeometry(QtCore.QRect(560, 430, 20, 171))
        self.det1_brice_label_2.setText("")
        self.det1_brice_label_2.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det1_brice_label_2.setObjectName("det1_brice_label_2")
        self.det1_answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det1_answer_label_2.setGeometry(QtCore.QRect(270, 490, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_answer_label_2.setFont(font)
        self.det1_answer_label_2.setText("")
        self.det1_answer_label_2.setObjectName("det1_answer_label_2")
        self.det1_argument_13_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_13_label.setGeometry(QtCore.QRect(470, 440, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_13_label.setFont(font)
        self.det1_argument_13_label.setText("")
        self.det1_argument_13_label.setObjectName("det1_argument_13_label")
        self.det1_answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.det1_answer_label_3.setGeometry(QtCore.QRect(270, 540, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_answer_label_3.setFont(font)
        self.det1_answer_label_3.setText("")
        self.det1_answer_label_3.setObjectName("det1_answer_label_3")
        self.det1_argument_33_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_33_label.setGeometry(QtCore.QRect(470, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_33_label.setFont(font)
        self.det1_argument_33_label.setText("")
        self.det1_argument_33_label.setObjectName("det1_argument_33_label")
        self.det1_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det1_brice_label_1.setGeometry(QtCore.QRect(260, 430, 20, 171))
        self.det1_brice_label_1.setText("")
        self.det1_brice_label_1.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det1_brice_label_1.setObjectName("det1_brice_label_1")
        self.det1_argument_23_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_23_label.setGeometry(QtCore.QRect(470, 490, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_23_label.setFont(font)
        self.det1_argument_23_label.setText("")
        self.det1_argument_23_label.setObjectName("det1_argument_23_label")
        self.det1_argument_32_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_argument_32_label.setGeometry(QtCore.QRect(370, 540, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_argument_32_label.setFont(font)
        self.det1_argument_32_label.setText("")
        self.det1_argument_32_label.setObjectName("det1_argument_32_label")
        self.det1_index_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_index_label.setGeometry(QtCore.QRect(210, 500, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.det1_index_label.setFont(font)
        self.det1_index_label.setObjectName("det1_index_label")
        self.det2_argument_33_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_33_label.setGeometry(QtCore.QRect(1250, 330, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_33_label.setFont(font)
        self.det2_argument_33_label.setText("")
        self.det2_argument_33_label.setObjectName("det2_argument_33_label")
        self.det2_argument_13_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_13_label.setGeometry(QtCore.QRect(1250, 230, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_13_label.setFont(font)
        self.det2_argument_13_label.setText("")
        self.det2_argument_13_label.setObjectName("det2_argument_13_label")
        self.det2_argument_11_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_11_label.setGeometry(QtCore.QRect(1050, 230, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_11_label.setFont(font)
        self.det2_argument_11_label.setText("")
        self.det2_argument_11_label.setObjectName("det2_argument_11_label")
        self.det_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det_2_label.setGeometry(QtCore.QRect(1390, 260, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_2_label.setFont(font)
        self.det_2_label.setText("")
        self.det_2_label.setObjectName("det_2_label")
        self.det2_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det2_brice_label_1.setGeometry(QtCore.QRect(1040, 220, 20, 171))
        self.det2_brice_label_1.setText("")
        self.det2_brice_label_1.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det2_brice_label_1.setObjectName("det2_brice_label_1")
        self.det2_answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.det2_answer_label_3.setGeometry(QtCore.QRect(1150, 330, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_answer_label_3.setFont(font)
        self.det2_answer_label_3.setText("")
        self.det2_answer_label_3.setObjectName("det2_answer_label_3")
        self.det2_answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det2_answer_label_1.setGeometry(QtCore.QRect(1150, 230, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_answer_label_1.setFont(font)
        self.det2_answer_label_1.setText("")
        self.det2_answer_label_1.setObjectName("det2_answer_label_1")
        self.det2_argument_21_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_21_label.setGeometry(QtCore.QRect(1050, 280, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_21_label.setFont(font)
        self.det2_argument_21_label.setText("")
        self.det2_argument_21_label.setObjectName("det2_argument_21_label")
        self.det2_answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det2_answer_label_2.setGeometry(QtCore.QRect(1150, 280, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_answer_label_2.setFont(font)
        self.det2_answer_label_2.setText("")
        self.det2_answer_label_2.setObjectName("det2_answer_label_2")
        self.det2_index_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_index_label.setGeometry(QtCore.QRect(990, 300, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.det2_index_label.setFont(font)
        self.det2_index_label.setObjectName("det2_index_label")
        self.det2_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det2_brice_label_2.setGeometry(QtCore.QRect(1340, 220, 20, 171))
        self.det2_brice_label_2.setText("")
        self.det2_brice_label_2.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det2_brice_label_2.setObjectName("det2_brice_label_2")
        self.det2_argument_23_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_23_label.setGeometry(QtCore.QRect(1250, 280, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_23_label.setFont(font)
        self.det2_argument_23_label.setText("")
        self.det2_argument_23_label.setObjectName("det2_argument_23_label")
        self.det2_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_triangle_label.setGeometry(QtCore.QRect(940, 280, 51, 41))
        self.det2_triangle_label.setText("")
        self.det2_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.det2_triangle_label.setObjectName("det2_triangle_label")
        self.det2_argument_31_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_argument_31_label.setGeometry(QtCore.QRect(1050, 330, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_argument_31_label.setFont(font)
        self.det2_argument_31_label.setText("")
        self.det2_argument_31_label.setObjectName("det2_argument_31_label")
        self.det_3_label = QtWidgets.QLabel(self.centralwidget)
        self.det_3_label.setGeometry(QtCore.QRect(1390, 460, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det_3_label.setFont(font)
        self.det_3_label.setText("")
        self.det_3_label.setObjectName("det_3_label")
        self.det3_argument_22_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_22_label.setGeometry(QtCore.QRect(1150, 480, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_22_label.setFont(font)
        self.det3_argument_22_label.setText("")
        self.det3_argument_22_label.setObjectName("det3_argument_22_label")
        self.det3_argument_31_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_31_label.setGeometry(QtCore.QRect(1050, 530, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_31_label.setFont(font)
        self.det3_argument_31_label.setText("")
        self.det3_argument_31_label.setObjectName("det3_argument_31_label")
        self.det3_brice_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det3_brice_label_2.setGeometry(QtCore.QRect(1340, 420, 20, 171))
        self.det3_brice_label_2.setText("")
        self.det3_brice_label_2.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det3_brice_label_2.setObjectName("det3_brice_label_2")
        self.det3_argument_32_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_32_label.setGeometry(QtCore.QRect(1150, 530, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_32_label.setFont(font)
        self.det3_argument_32_label.setText("")
        self.det3_argument_32_label.setObjectName("det3_argument_32_label")
        self.det3_brice_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det3_brice_label_1.setGeometry(QtCore.QRect(1040, 420, 20, 171))
        self.det3_brice_label_1.setText("")
        self.det3_brice_label_1.setPixmap(QtGui.QPixmap("verticalLine2.jpg"))
        self.det3_brice_label_1.setObjectName("det3_brice_label_1")
        self.det3_argument_21_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_21_label.setGeometry(QtCore.QRect(1050, 480, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_21_label.setFont(font)
        self.det3_argument_21_label.setText("")
        self.det3_argument_21_label.setObjectName("det3_argument_21_label")
        self.det3_index_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_index_label.setGeometry(QtCore.QRect(990, 510, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.det3_index_label.setFont(font)
        self.det3_index_label.setObjectName("det3_index_label")
        self.det3_argument_11_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_11_label.setGeometry(QtCore.QRect(1050, 430, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_11_label.setFont(font)
        self.det3_argument_11_label.setText("")
        self.det3_argument_11_label.setObjectName("det3_argument_11_label")
        self.det3_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_triangle_label.setGeometry(QtCore.QRect(940, 480, 51, 41))
        self.det3_triangle_label.setText("")
        self.det3_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.det3_triangle_label.setObjectName("det3_triangle_label")
        self.det3_answer_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.det3_answer_label_1.setGeometry(QtCore.QRect(1250, 430, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_answer_label_1.setFont(font)
        self.det3_answer_label_1.setText("")
        self.det3_answer_label_1.setObjectName("det3_answer_label_1")
        self.det3_argument_12_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_argument_12_label.setGeometry(QtCore.QRect(1150, 430, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_argument_12_label.setFont(font)
        self.det3_argument_12_label.setText("")
        self.det3_argument_12_label.setObjectName("det3_argument_12_label")
        self.det3_answer_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.det3_answer_label_2.setGeometry(QtCore.QRect(1250, 480, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_answer_label_2.setFont(font)
        self.det3_answer_label_2.setText("")
        self.det3_answer_label_2.setObjectName("det3_answer_label_2")
        self.det3_answer_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.det3_answer_label_3.setGeometry(QtCore.QRect(1250, 530, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_answer_label_3.setFont(font)
        self.det3_answer_label_3.setText("")
        self.det3_answer_label_3.setObjectName("det3_answer_label_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 30, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(290, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(200, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.x23_label = QtWidgets.QLabel(self.centralwidget)
        self.x23_label.setGeometry(QtCore.QRect(280, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x23_label.setFont(font)
        self.x23_label.setObjectName("x23_label")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(330, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.x33_label = QtWidgets.QLabel(self.centralwidget)
        self.x33_label.setGeometry(QtCore.QRect(410, 120, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x33_label.setFont(font)
        self.x33_label.setObjectName("x33_label")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(460, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(400, 80, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.det2_equals_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_equals_2_label.setGeometry(QtCore.QRect(1350, 280, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_equals_2_label.setFont(font)
        self.det2_equals_2_label.setObjectName("det2_equals_2_label")
        self.main_det_equals_1 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_equals_1.setGeometry(QtCore.QRect(220, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_equals_1.setFont(font)
        self.main_det_equals_1.setObjectName("main_det_equals_1")
        self.det2_equals_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det2_equals_1_label.setGeometry(QtCore.QRect(1000, 280, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det2_equals_1_label.setFont(font)
        self.det2_equals_1_label.setObjectName("det2_equals_1_label")
        self.det1_equals_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_equals_1_label.setGeometry(QtCore.QRect(220, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_equals_1_label.setFont(font)
        self.det1_equals_1_label.setObjectName("det1_equals_1_label")
        self.det3_equals_1_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_equals_1_label.setGeometry(QtCore.QRect(1000, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_equals_1_label.setFont(font)
        self.det3_equals_1_label.setObjectName("det3_equals_1_label")
        self.det1_equals_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det1_equals_2_label.setGeometry(QtCore.QRect(570, 490, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det1_equals_2_label.setFont(font)
        self.det1_equals_2_label.setObjectName("det1_equals_2_label")
        self.det3_equals_2_label = QtWidgets.QLabel(self.centralwidget)
        self.det3_equals_2_label.setGeometry(QtCore.QRect(1350, 480, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.det3_equals_2_label.setFont(font)
        self.det3_equals_2_label.setObjectName("det3_equals_2_label")
        self.main_det_arg_33 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_33.setGeometry(QtCore.QRect(470, 350, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_33.setFont(font)
        self.main_det_arg_33.setText("")
        self.main_det_arg_33.setObjectName("main_det_arg_33")
        self.main_det_arg_32 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_32.setGeometry(QtCore.QRect(370, 350, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_32.setFont(font)
        self.main_det_arg_32.setText("")
        self.main_det_arg_32.setObjectName("main_det_arg_32")
        self.main_det_arg_21 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_21.setGeometry(QtCore.QRect(270, 300, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_21.setFont(font)
        self.main_det_arg_21.setText("")
        self.main_det_arg_21.setObjectName("main_det_arg_21")
        self.main_det_arg_22 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_22.setGeometry(QtCore.QRect(370, 300, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_22.setFont(font)
        self.main_det_arg_22.setText("")
        self.main_det_arg_22.setObjectName("main_det_arg_22")
        self.main_det_arg_12 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_12.setGeometry(QtCore.QRect(370, 250, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_12.setFont(font)
        self.main_det_arg_12.setText("")
        self.main_det_arg_12.setObjectName("main_det_arg_12")
        self.main_det_arg_13 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_13.setGeometry(QtCore.QRect(470, 250, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_13.setFont(font)
        self.main_det_arg_13.setText("")
        self.main_det_arg_13.setObjectName("main_det_arg_13")
        self.main_det_arg_31 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_31.setGeometry(QtCore.QRect(270, 350, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_31.setFont(font)
        self.main_det_arg_31.setText("")
        self.main_det_arg_31.setObjectName("main_det_arg_31")
        self.main_det_arg_23 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_23.setGeometry(QtCore.QRect(470, 300, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_23.setFont(font)
        self.main_det_arg_23.setText("")
        self.main_det_arg_23.setObjectName("main_det_arg_23")
        self.main_det_arg_11 = QtWidgets.QLabel(self.centralwidget)
        self.main_det_arg_11.setGeometry(QtCore.QRect(270, 250, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.main_det_arg_11.setFont(font)
        self.main_det_arg_11.setText("")
        self.main_det_arg_11.setObjectName("main_det_arg_11")
        self.x1_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_label.setGeometry(QtCore.QRect(160, 680, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_label.setFont(font)
        self.x1_label.setObjectName("x1_label")
        self.x2_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_label.setGeometry(QtCore.QRect(690, 660, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_label.setFont(font)
        self.x2_label.setObjectName("x2_label")
        self.x3_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_label.setGeometry(QtCore.QRect(1210, 660, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_label.setFont(font)
        self.x3_label.setObjectName("x3_label")
        self.x1_equals_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_equals_label.setGeometry(QtCore.QRect(210, 700, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_equals_label.setFont(font)
        self.x1_equals_label.setObjectName("x1_equals_label")
        self.x2_equals_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_equals_label.setGeometry(QtCore.QRect(740, 680, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_equals_label.setFont(font)
        self.x2_equals_label.setObjectName("x2_equals_label")
        self.x3_equals_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_equals_label.setGeometry(QtCore.QRect(1260, 670, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_equals_label.setFont(font)
        self.x3_equals_label.setObjectName("x3_equals_label")
        self.x1_main_triangle_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_main_triangle_det_label.setGeometry(QtCore.QRect(260, 720, 51, 41))
        self.x1_main_triangle_det_label.setText("")
        self.x1_main_triangle_det_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x1_main_triangle_det_label.setObjectName("x1_main_triangle_det_label")
        self.x1_det1_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_det1_triangle_label.setGeometry(QtCore.QRect(260, 660, 51, 41))
        self.x1_det1_triangle_label.setText("")
        self.x1_det1_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x1_det1_triangle_label.setObjectName("x1_det1_triangle_label")
        self.x1_det_index_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_det_index_label.setGeometry(QtCore.QRect(310, 680, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.x1_det_index_label.setFont(font)
        self.x1_det_index_label.setObjectName("x1_det_index_label")
        self.x1_divide_line_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_divide_line_label.setGeometry(QtCore.QRect(250, 700, 81, 19))
        self.x1_divide_line_label.setObjectName("x1_divide_line_label")
        self.x2_divide_line_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_divide_line_label.setGeometry(QtCore.QRect(780, 690, 81, 19))
        self.x2_divide_line_label.setObjectName("x2_divide_line_label")
        self.x3_divide_line_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_divide_line_label.setGeometry(QtCore.QRect(1310, 680, 81, 19))
        self.x3_divide_line_label.setObjectName("x3_divide_line_label")
        self.x2_main_triangle_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_main_triangle_det_label.setGeometry(QtCore.QRect(790, 710, 51, 41))
        self.x2_main_triangle_det_label.setText("")
        self.x2_main_triangle_det_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x2_main_triangle_det_label.setObjectName("x2_main_triangle_det_label")
        self.x3_main_triangle_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_main_triangle_det_label.setGeometry(QtCore.QRect(1320, 700, 51, 41))
        self.x3_main_triangle_det_label.setText("")
        self.x3_main_triangle_det_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x3_main_triangle_det_label.setObjectName("x3_main_triangle_det_label")
        self.x2_det_index_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_det_index_label.setGeometry(QtCore.QRect(840, 670, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.x2_det_index_label.setFont(font)
        self.x2_det_index_label.setObjectName("x2_det_index_label")
        self.x2_det2_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_det2_triangle_label.setGeometry(QtCore.QRect(790, 650, 51, 41))
        self.x2_det2_triangle_label.setText("")
        self.x2_det2_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x2_det2_triangle_label.setObjectName("x2_det2_triangle_label")
        self.x3_det3_triangle_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_det3_triangle_label.setGeometry(QtCore.QRect(1320, 640, 51, 41))
        self.x3_det3_triangle_label.setText("")
        self.x3_det3_triangle_label.setPixmap(QtGui.QPixmap("triangle_2.png"))
        self.x3_det3_triangle_label.setObjectName("x3_det3_triangle_label")
        self.x3_det_index_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_det_index_label.setGeometry(QtCore.QRect(1370, 670, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.x3_det_index_label.setFont(font)
        self.x3_det_index_label.setObjectName("x3_det_index_label")
        self.x1_equals2_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_equals2_label.setGeometry(QtCore.QRect(330, 700, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_equals2_label.setFont(font)
        self.x1_equals2_label.setObjectName("x1_equals2_label")
        self.x2_equals2_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_equals2_label.setGeometry(QtCore.QRect(870, 690, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_equals2_label.setFont(font)
        self.x2_equals2_label.setObjectName("x2_equals2_label")
        self.x1_divide_line2_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_divide_line2_label.setGeometry(QtCore.QRect(370, 700, 121, 19))
        self.x1_divide_line2_label.setObjectName("x1_divide_line2_label")
        self.x1_det1_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_det1_label.setGeometry(QtCore.QRect(370, 640, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_det1_label.setFont(font)
        self.x1_det1_label.setText("")
        self.x1_det1_label.setObjectName("x1_det1_label")
        self.x3_equals2_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_equals2_label.setGeometry(QtCore.QRect(1400, 670, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_equals2_label.setFont(font)
        self.x3_equals2_label.setObjectName("x3_equals2_label")
        self.x1_main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_main_det_label.setGeometry(QtCore.QRect(370, 720, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_main_det_label.setFont(font)
        self.x1_main_det_label.setText("")
        self.x1_main_det_label.setObjectName("x1_main_det_label")
        self.x1_result_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_result_label.setGeometry(QtCore.QRect(530, 680, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_result_label.setFont(font)
        self.x1_result_label.setText("")
        self.x1_result_label.setObjectName("x1_result_label")
        self.x1_equals3_label = QtWidgets.QLabel(self.centralwidget)
        self.x1_equals3_label.setGeometry(QtCore.QRect(490, 700, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x1_equals3_label.setFont(font)
        self.x1_equals3_label.setObjectName("x1_equals3_label")
        self.x2_main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_main_det_label.setGeometry(QtCore.QRect(910, 710, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_main_det_label.setFont(font)
        self.x2_main_det_label.setText("")
        self.x2_main_det_label.setObjectName("x2_main_det_label")
        self.x2_divide_line2_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_divide_line2_label.setGeometry(QtCore.QRect(910, 690, 121, 19))
        self.x2_divide_line2_label.setObjectName("x2_divide_line2_label")
        self.x2_det2_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_det2_label.setGeometry(QtCore.QRect(910, 630, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_det2_label.setFont(font)
        self.x2_det2_label.setText("")
        self.x2_det2_label.setObjectName("x2_det2_label")
        self.x2_equals3_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_equals3_label.setGeometry(QtCore.QRect(1040, 690, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_equals3_label.setFont(font)
        self.x2_equals3_label.setObjectName("x2_equals3_label")
        self.x2_result_label = QtWidgets.QLabel(self.centralwidget)
        self.x2_result_label.setGeometry(QtCore.QRect(1070, 670, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x2_result_label.setFont(font)
        self.x2_result_label.setText("")
        self.x2_result_label.setObjectName("x2_result_label")
        self.x3_main_det_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_main_det_label.setGeometry(QtCore.QRect(1440, 700, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_main_det_label.setFont(font)
        self.x3_main_det_label.setText("")
        self.x3_main_det_label.setObjectName("x3_main_det_label")
        self.x3_equals3_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_equals3_label.setGeometry(QtCore.QRect(1560, 670, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_equals3_label.setFont(font)
        self.x3_equals3_label.setObjectName("x3_equals3_label")
        self.x3_det3_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_det3_label.setGeometry(QtCore.QRect(1440, 620, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_det3_label.setFont(font)
        self.x3_det3_label.setText("")
        self.x3_det3_label.setObjectName("x3_det3_label")
        self.x3_result_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_result_label.setGeometry(QtCore.QRect(1600, 650, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.x3_result_label.setFont(font)
        self.x3_result_label.setText("")
        self.x3_result_label.setObjectName("x3_result_label")
        self.x3_divide_line2_label = QtWidgets.QLabel(self.centralwidget)
        self.x3_divide_line2_label.setGeometry(QtCore.QRect(1440, 680, 121, 19))
        self.x3_divide_line2_label.setObjectName("x3_divide_line2_label")
        self.brace_label = QtWidgets.QLabel(self.centralwidget)
        self.brace_label.setGeometry(QtCore.QRect(60, 20, 41, 161))
        self.brace_label.setText("")
        self.brace_label.setObjectName("brace_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "="))
        self.argument_label_23.setText(_translate("MainWindow", "6"))
        self.argument_label_12.setText(_translate("MainWindow", "1"))
        self.argument_label_33.setText(_translate("MainWindow", "18"))
        self.answer_label_2.setText(_translate("MainWindow", "132"))
        self.answer_label_3.setText(_translate("MainWindow", "536"))
        self.label_3.setText(_translate("MainWindow", "+"))
        self.argument_label_32.setText(_translate("MainWindow", "23"))
        self.answer_label_1.setText(_translate("MainWindow", "77"))
        self.argument_label_13.setText(_translate("MainWindow", "2"))
        self.x22_label.setText(_translate("MainWindow", "x2"))
        self.x12_label.setText(_translate("MainWindow", "x1"))
        self.x32_label.setText(_translate("MainWindow", "x3"))
        self.argument_label_11.setText(_translate("MainWindow", "5"))
        self.argument_label_31.setText(_translate("MainWindow", "12"))
        self.x13_label.setText(_translate("MainWindow", "x1"))
        self.argument_label_22.setText(_translate("MainWindow", "3"))
        self.argument_label_21.setText(_translate("MainWindow", "4"))
        self.x11_label.setText(_translate("MainWindow", "x1"))
        self.x21_label.setText(_translate("MainWindow", "x2"))
        self.x31_label.setText(_translate("MainWindow", "x3"))
        self.pushButton.setText(_translate("MainWindow", "next"))
        self.main_det_equals_2.setText(_translate("MainWindow", "="))
        self.det1_index_label.setText(_translate("MainWindow", "1"))
        self.det2_index_label.setText(_translate("MainWindow", "2"))
        self.det3_index_label.setText(_translate("MainWindow", "3"))
        self.label_8.setText(_translate("MainWindow", "+"))
        self.label_6.setText(_translate("MainWindow", "+"))
        self.label_10.setText(_translate("MainWindow", "+"))
        self.label_19.setText(_translate("MainWindow", "+"))
        self.x23_label.setText(_translate("MainWindow", "x2"))
        self.label_21.setText(_translate("MainWindow", "+"))
        self.x33_label.setText(_translate("MainWindow", "x3"))
        self.label_22.setText(_translate("MainWindow", "="))
        self.label_16.setText(_translate("MainWindow", "="))
        self.det2_equals_2_label.setText(_translate("MainWindow", "="))
        self.main_det_equals_1.setText(_translate("MainWindow", "="))
        self.det2_equals_1_label.setText(_translate("MainWindow", "="))
        self.det1_equals_1_label.setText(_translate("MainWindow", "="))
        self.det3_equals_1_label.setText(_translate("MainWindow", "="))
        self.det1_equals_2_label.setText(_translate("MainWindow", "="))
        self.det3_equals_2_label.setText(_translate("MainWindow", "="))
        self.x1_label.setText(_translate("MainWindow", "x1"))
        self.x2_label.setText(_translate("MainWindow", "x2"))
        self.x3_label.setText(_translate("MainWindow", "x3"))
        self.x1_equals_label.setText(_translate("MainWindow", "="))
        self.x2_equals_label.setText(_translate("MainWindow", "="))
        self.x3_equals_label.setText(_translate("MainWindow", "="))
        self.x1_det_index_label.setText(_translate("MainWindow", "1"))
        self.x1_divide_line_label.setText(_translate("MainWindow", "------------"))
        self.x2_divide_line_label.setText(_translate("MainWindow", "------------"))
        self.x3_divide_line_label.setText(_translate("MainWindow", "------------"))
        self.x2_det_index_label.setText(_translate("MainWindow", "2"))
        self.x3_det_index_label.setText(_translate("MainWindow", "3"))
        self.x1_equals2_label.setText(_translate("MainWindow", "="))
        self.x2_equals2_label.setText(_translate("MainWindow", "="))
        self.x1_divide_line2_label.setText(_translate("MainWindow", "------------------"))
        self.x3_equals2_label.setText(_translate("MainWindow", "="))
        self.x1_equals3_label.setText(_translate("MainWindow", "="))
        self.x2_divide_line2_label.setText(_translate("MainWindow", "------------------"))
        self.x2_equals3_label.setText(_translate("MainWindow", "="))
        self.x3_equals3_label.setText(_translate("MainWindow", "="))
        self.x3_divide_line2_label.setText(_translate("MainWindow", "------------------"))
